#!/usr/bin/env python3
"""Main-text LaTeX tables (COLM 2026).

Emits two tables from the existing ``unified_all_suites.json`` files:

* ``tab_main_results.tex`` — Table 1 (14 models x 5 suites,
  Acc10 + Disc_delta), with bold per-suite maxima for both metrics.
* ``tab_uai_pathway.tex`` — Table 2 (suite-mean UAI by pathway and
  relevance + Wilcoxon p_BH).

Outputs are written to ``outputs/tables/`` by default.

Usage:
    python scripts/eval/paper/tables_main.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from _common import (
    ALL_MODELS_ORDER,
    DEFAULT_API_RESULTS,
    DEFAULT_OW_RESULTS,
    DEFAULT_TABLE_DIR,
    SUITES,
    SUITE_LATEX,
    collect_per_suite,
    fmt_num,
    fmt_pct,
    short_to_latex,
    write_table,
)

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))
from anchorbench_eval.metrics import bh_correction, paired_wilcoxon  # noqa: E402


def load_unified(*paths: Path) -> list[dict]:
    out: list[dict] = []
    for p in paths:
        with open(p) as f:
            out.extend(json.load(f))
    return out


def build_main_results(unified: list[dict]) -> str:
    by_suite = {s: collect_per_suite(unified, s) for s in SUITES}

    max_acc: dict[str, float] = {}
    max_disc: dict[str, float] = {}
    for s in SUITES:
        accs = [r["acc10_control"] for r in by_suite[s].values()
                if r.get("acc10_control") is not None]
        discs = [r["disc_delta"] for r in by_suite[s].values()
                 if r.get("disc_delta") is not None]
        max_acc[s] = max(accs) if accs else None
        max_disc[s] = max(discs) if discs else None

    def cell(model: str, suite: str) -> tuple[str, str]:
        r = by_suite[suite].get(model)
        if r is None:
            return ("---", "---")
        acc = r.get("acc10_control")
        disc = r.get("disc_delta")
        acc_s = fmt_pct(acc)
        disc_s = fmt_num(disc, 2)
        if acc is not None and max_acc[suite] is not None and abs(acc - max_acc[suite]) < 1e-6:
            acc_s = f"\\textbf{{{acc_s}}}"
        if disc is not None and max_disc[suite] is not None and abs(disc - max_disc[suite]) < 1e-6:
            disc_s = f"\\textbf{{{disc_s}}}"
        return (acc_s, disc_s)

    lines: list[str] = []
    lines.append("% Table 1: main results (Acc10 + Disc_delta).")
    lines.append("% Auto-generated by scripts/eval/paper/tables_main.py.")
    lines.append("\\begin{table*}[t]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\setlength{\\tabcolsep}{2pt}")
    lines.append("  \\resizebox{0.96\\textwidth}{!}{%")
    lines.append("    \\tablestartstriped{4}")
    lines.append("    \\begin{tabular}{@{}lrrrrrrrrrr@{}}")
    lines.append("      \\toprule")
    lines.append("      \\rowcolor{white}")
    lines.append("      \\multicolumn{1}{c}{\\multirow{2}{*}{\\cellcolor{white}\\textbf{Model}}}")
    lines.append("      &")
    lines.append("      \\multicolumn{2}{c}{" + SUITE_LATEX["External"] + "} &")
    lines.append("      \\multicolumn{2}{c}{" + SUITE_LATEX["History"] + "} &")
    lines.append("      \\multicolumn{2}{c}{" + SUITE_LATEX["Icl"] + "} &")
    lines.append("      \\multicolumn{2}{c}{" + SUITE_LATEX["Rag"] + "} &")
    lines.append("      \\multicolumn{2}{c}{" + SUITE_LATEX["Tool"] + "} \\\\")
    lines.append("      \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}")
    lines.append("      \\cmidrule(lr){8-9}\\cmidrule(lr){10-11}")
    lines.append("      \\rowcolor{white}")
    lines.append("      "
                 "& Acc$_{10}$ (\\%) & Disc$_{\\Delta}$"
                 " & Acc$_{10}$ (\\%) & Disc$_{\\Delta}$"
                 " & Acc$_{10}$ (\\%) & Disc$_{\\Delta}$"
                 " & Acc$_{10}$ (\\%) & Disc$_{\\Delta}$"
                 " & Acc$_{10}$ (\\%) & Disc$_{\\Delta}$ \\\\")
    lines.append("      \\midrule")

    family_breaks = {"Llama-1B", "Gemma-1B", "OLMo-13B", "GPT-5.4-mini"}
    for model in ALL_MODELS_ORDER:
        if model in family_breaks:
            lines.append("      \\midrule")
        cells: list[str] = [short_to_latex(model)]
        for s in ("External", "History", "Icl", "Rag", "Tool"):
            acc_s, disc_s = cell(model, s)
            cells.extend([acc_s, disc_s])
        lines.append("      " + " & ".join(cells) + " \\\\")

    lines.append("      \\bottomrule")
    lines.append("    \\end{tabular}")
    lines.append("    \\tablestopstriped")
    lines.append("  }")
    lines.append("  \\caption{Task accuracy (Acc$_{10}$, control-only) and")
    lines.append("    discrimination (Disc$_{\\Delta}$) for fourteen models")
    lines.append("    across five suites. Bold marks highest per suite.}")
    lines.append("  \\label{tab:main_results}")
    lines.append("\\end{table*}")
    return "\n".join(lines)


def build_uai_pathway(unified: list[dict]) -> str:
    """Table 2: suite-mean UAI_irr, UAI_pls, Disc_delta + Wilcoxon p_BH."""
    rows: list[tuple[str, float, float, float, float]] = []
    suite_order = ["External", "History", "Rag", "Tool", "Icl"]
    pathway_pvals: list[float] = []
    intermediate: list[tuple[str, float, float, float]] = []

    for suite in suite_order:
        cells = [r for r in unified if r.get("suite") == suite]
        irrs = [r["uai_irr"] for r in cells if r.get("uai_irr") is not None]
        pls = [r["uai_plaus"] for r in cells if r.get("uai_plaus") is not None]
        discs = [r["disc_delta"] for r in cells
                 if r.get("disc_delta") is not None]
        if not irrs or not pls:
            continue

        n = min(len(irrs), len(pls))
        pls_arr = np.array(pls[:n])
        irr_arr = np.array(irrs[:n])
        p = paired_wilcoxon(pls_arr, irr_arr)
        intermediate.append((
            suite,
            float(np.mean(irr_arr)),
            float(np.mean(pls_arr)),
            float(np.mean(discs)) if discs else float("nan"),
        ))
        pathway_pvals.append(p)

    valid = [(i, p) for i, p in enumerate(pathway_pvals)
             if p is not None and not np.isnan(p)]
    if valid:
        adj = bh_correction([p for _, p in valid])
        adj_full: list[float | None] = list(pathway_pvals)
        for (idx, _), a in zip(valid, adj):
            adj_full[idx] = a
    else:
        adj_full = pathway_pvals

    def fmt_p(p: float | None) -> str:
        if p is None or (isinstance(p, float) and np.isnan(p)):
            return "n.s."
        if p < 0.01:
            return "$<$0.01"
        if p < 0.05:
            return "$\\approx${:.2f}".format(p)
        return "{:.2f}".format(p)

    lines: list[str] = []
    lines.append("% Table 2: UAI by pathway (mean over models) + Wilcoxon p_BH.")
    lines.append("% Auto-generated by scripts/eval/paper/tables_main.py.")
    lines.append("\\begin{table}[t]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lcccc@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Pathway}")
    lines.append("    & \\textbf{UAI\\textsubscript{irr}}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls}}")
    lines.append("    & \\textbf{Disc$_{\\Delta}$}")
    lines.append("    & \\textbf{$p_{\\mathrm{BH}}$} \\\\")
    lines.append("    \\midrule")
    for (suite, irr, pls, disc), p_adj in zip(intermediate, adj_full):
        if np.isnan(disc):
            disc_s = "---"
        elif abs(disc) >= 0.05:
            disc_s = f"\\textbf{{{disc:.2f}}}"
        else:
            disc_s = f"{disc:.2f}"
        lines.append(f"    {SUITE_LATEX[suite]:<14} & {irr:.2f} & {pls:.2f} & {disc_s} & {fmt_p(p_adj)} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Mean anchor influence by pathway and relevance")
    lines.append("    ($n{=}14$ models per pathway, $n{=}13$ on Tool).")
    lines.append("    Disc$_{\\Delta}$ is the plausible--irrelevant gap;")
    lines.append("    $p$-values are Wilcoxon signed-rank tests (BH-corrected).}")
    lines.append("  \\label{tab:uai-pathway}")
    lines.append("\\end{table}")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--ow_unified", type=Path,
                   default=DEFAULT_OW_RESULTS / "unified_all_suites.json")
    p.add_argument("--api_unified", type=Path,
                   default=DEFAULT_API_RESULTS / "unified_all_suites.json")
    p.add_argument("--out_dir", type=Path, default=DEFAULT_TABLE_DIR)
    args = p.parse_args()

    unified = load_unified(args.ow_unified, args.api_unified)
    print(f"Loaded {len(unified)} model-suite cells from unified files")

    write_table(args.out_dir / "tab_main_results.tex",
                build_main_results(unified))
    write_table(args.out_dir / "tab_uai_pathway.tex",
                build_uai_pathway(unified))


if __name__ == "__main__":
    main()
