#!/usr/bin/env python3
"""Appendix LaTeX tables (COLM 2026).

Emits the following from existing ``unified_all_suites.json`` files
plus a small number of per-record JSONL passes for distribution and
boundary analyses:

* ``tab_app_external.tex``, ``tab_app_history.tex``, ``tab_app_icl.tex``,
  ``tab_app_rag.tex``, ``tab_app_tool.tex`` — Tables 4-8: full per-suite
  metrics for all 14 models.
* ``tab_uai_summary.tex`` — Table 9: cross-suite UAI summary + ICL-dist row.
* ``tab_stats_inference.tex`` — Table 10: contrasts with bootstrap CIs.
* ``tab_uai_distribution.tex`` — Table 11: pooled per-item UAI distribution.
* ``tab_anchored_mae.tex`` — Table 12: Delta-MAE by relevance and suite.
* ``tab_history_matched.tex`` — Table 13: matched-control History analysis.
* ``tab_icl_dist.tex`` — Table 14: ICL-metadata vs ICL-dist comparison.
* ``tab_tool_plaintext.tex`` — Table 15: structured vs plaintext Tool format.
* ``tab_difficulty.tex`` — Table 16: easy vs hard items by suite.
* ``tab_boundary.tex`` — boundary-clipping subtable.
* ``tab_model_details.tex`` — model panel description from anchorbench.eval.constants.

Outputs are written to ``outputs/tables/`` by default.

Usage:
    python anchorbench.paper.tables_appendix
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from anchorbench.eval.constants import (
    API_MODEL_IDS,
    OW_MODEL_IDS,
)
from anchorbench.eval.io import load_records
from anchorbench.eval.metrics import (
    bh_correction,
    bootstrap_ci,
    compute_unified_metrics,
    group_by_item,
    paired_wilcoxon,
)

from ._common import (
    ALL_MODELS_ORDER,
    DEFAULT_API_RESULTS,
    DEFAULT_ICL_DIST_API,
    DEFAULT_ICL_DIST_OW,
    DEFAULT_OW_RESULTS,
    DEFAULT_TABLE_DIR,
    OW_MODELS_ORDER,
    SUITE_LATEX,
    collect_per_suite,
    discover_jsonl,
    fmt_num,
    fmt_pct1,
    short_to_latex,
    write_table,
)

# ---------------------------------------------------------------------------
# Per-suite tables (Tables 4-8, app:external ... app:tool)
# ---------------------------------------------------------------------------

def build_per_suite_table(unified: list[dict], suite: str, label: str,
                          caption: str) -> str:
    by_model = collect_per_suite(unified, suite)
    lines: list[str] = []
    lines.append(f"% Auto-generated by anchorbench.paper.tables_appendix "
                 f"-- {suite} per-suite results")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\tablestartstriped{3}")
    lines.append("  \\begin{tabular}{@{}lrrrrrrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Model}")
    lines.append("    & \\textbf{MAE\\textsubscript{c}}$\\,\\downarrow$")
    lines.append("    & \\textbf{Acc\\textsubscript{10} (\\%)}$\\,\\uparrow$")
    lines.append("    & \\textbf{UAI\\textsubscript{irr}}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls}}")
    lines.append("    & \\textbf{TAR\\textsubscript{irr}}")
    lines.append("    & \\textbf{TAR\\textsubscript{pls}}")
    lines.append("    & \\textbf{Disc$_{\\Delta}$}")
    lines.append("    & \\textbf{Parse} \\\\")
    lines.append("    \\midrule")

    family_breaks = {"Llama-1B", "Gemma-1B", "OLMo-13B", "GPT-5.4-mini"}
    for model in ALL_MODELS_ORDER:
        if model in family_breaks:
            lines.append("    \\midrule")
        r = by_model.get(model)
        latex_name = short_to_latex(model)
        if r is None or r.get("parse_rate", 0) < 0.05:
            parse = r.get("parse_rate") if r else None
            parse_s = f"{parse:.2f}" if parse is not None else "---"
            lines.append(
                f"    {latex_name:<16} & ---   & ---  & ---   & ---  & ---  "
                f"& ---  & ---  & {parse_s} \\\\"
            )
            continue
        mae = fmt_num(r.get("mae_control"), 2)
        acc = fmt_pct1(r.get("acc10_control"))
        ui = fmt_num(r.get("uai_irr"), 2)
        up = fmt_num(r.get("uai_plaus"), 2)
        ti = fmt_num(r.get("tar_irr"), 2)
        tp = fmt_num(r.get("tar_plaus"), 2)
        dd = fmt_num(r.get("disc_delta"), 2)
        pr = (f"{r.get('parse_rate'):.2f}"
              if r.get("parse_rate") is not None else "---")
        lines.append(
            f"    {latex_name:<16} & {mae} & {acc} & {ui}  & {up} & {ti} & {tp} & {dd} & {pr} \\\\"
        )

    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\tablestopstriped")
    lines.append(f"  \\caption{{{caption}}}")
    lines.append(f"  \\label{{{label}}}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 9: tab:uai_summary
# ---------------------------------------------------------------------------

def build_uai_summary(
    unified: list[dict],
    icl_dist_metrics: list[dict] | None = None,
) -> str:
    rows: list[tuple[str, float, float, float, str]] = []
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        cells = [r for r in unified if r.get("suite") == suite]
        irrs = [r["uai_irr"] for r in cells if r.get("uai_irr") is not None]
        pls = [r["uai_plaus"] for r in cells if r.get("uai_plaus") is not None]
        discs = [r["disc_delta"] for r in cells
                 if r.get("disc_delta") is not None]
        if not discs:
            continue
        n_pos = sum(1 for d in discs if d > 0)
        suite_label = SUITE_LATEX[suite]
        if suite == "Icl":
            suite_label = SUITE_LATEX[suite] + " (metadata)"
        rows.append((
            suite_label,
            float(np.mean(irrs)),
            float(np.mean(pls)),
            float(np.mean(discs)),
            f"{n_pos}/{len(discs)}",
        ))
        if suite == "Icl" and icl_dist_metrics:
            irrs_d = [m["uai_irr"] for m in icl_dist_metrics if m.get("uai_irr") is not None]
            pls_d = [m["uai_plaus"] for m in icl_dist_metrics if m.get("uai_plaus") is not None]
            discs_d = [m["disc_delta"] for m in icl_dist_metrics if m.get("disc_delta") is not None]
            if discs_d:
                n_pos_d = sum(1 for d in discs_d if d > 0)
                rows.append((
                    SUITE_LATEX["Icl"] + " (ICL-dist)",
                    float(np.mean(irrs_d)),
                    float(np.mean(pls_d)),
                    float(np.mean(discs_d)),
                    f"{n_pos_d}/{len(discs_d)}",
                ))

    excl_rows = [r for r in rows if "ICL-dist" not in r[0]]
    irrs_all = [r[1] for r in excl_rows]
    pls_all = [r[2] for r in excl_rows]
    discs_all = [r[3] for r in excl_rows]
    pos_total = sum(int(r[4].split("/")[0]) for r in excl_rows)
    n_total = sum(int(r[4].split("/")[1]) for r in excl_rows)

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lrrrl@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Suite}")
    lines.append("    & \\textbf{UAI\\textsubscript{irr}}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls}}")
    lines.append("    & \\textbf{Disc$_{\\Delta}$}")
    lines.append("    & \\textbf{$\\frac{+}{n}$} \\\\")
    lines.append("    \\midrule")
    for label, irr, pls, disc, frac in rows:
        lines.append(f"    {label:<28} & {irr:5.2f} & {pls:5.2f} & {disc:5.2f} & {frac} \\\\")
    lines.append("    \\midrule")
    lines.append(
        f"    \\textit{{All (excl.\\ ICL-dist)}} & {np.mean(irrs_all):.2f}  "
        f"& {np.mean(pls_all):.2f} & {np.mean(discs_all):.2f} & {pos_total}/{n_total} \\\\"
    )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Mean anchoring influence by relevance and suite.")
    lines.append("    $+/n$: cells with Disc$_{\\Delta} > 0$.")
    lines.append("    ICL-dist uses distribution-matching demonstrations")
    lines.append("    (open-weight models only).}")
    lines.append("  \\label{tab:uai_summary}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 10: tab:stats_inference
# ---------------------------------------------------------------------------

def build_stats_inference(unified: list[dict]) -> str:
    suite_rows = []
    pvals_for_bh: list[float] = []
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        cells = [r for r in unified if r.get("suite") == suite]
        pls_arr = np.array([r["uai_plaus"] for r in cells
                            if r.get("uai_plaus") is not None])
        irr_arr = np.array([r["uai_irr"] for r in cells
                            if r.get("uai_irr") is not None])
        n = min(len(pls_arr), len(irr_arr))
        if n < 2:
            continue
        diffs = (pls_arr[:n] - irr_arr[:n]).tolist()
        mean, lo, hi = bootstrap_ci(diffs)
        p = paired_wilcoxon(pls_arr[:n], irr_arr[:n])
        suite_rows.append((suite, mean, lo, hi, p))
        pvals_for_bh.append(p)
    valid = [(i, p) for i, p in enumerate(pvals_for_bh)
             if p is not None and not np.isnan(p)]
    bh_full = list(pvals_for_bh)
    if valid:
        adj = bh_correction([p for _, p in valid])
        for (idx, _), a in zip(valid, adj):
            bh_full[idx] = a

    def fmt_p(p: float | None) -> str:
        if p is None or (isinstance(p, float) and np.isnan(p)):
            return "n.s."
        if p < 0.01:
            return "$<$0.01"
        if p < 0.05:
            return f"{p:.2f}"
        return f"{p:.2f}"

    suite_means: dict[str, float] = {}
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        ow_cells = [r["disc_delta"] for r in unified
                    if r.get("suite") == suite
                    and r["model"] in OW_MODELS_ORDER
                    and r.get("disc_delta") is not None]
        if ow_cells:
            suite_means[suite] = float(np.mean(ow_cells))
    suite_means_arr = np.array(list(suite_means.values()))
    if len(suite_means_arr) > 1:
        rng_mean = float(suite_means_arr.max() - suite_means_arr.min())
        rng_boots = []
        rs = np.random.RandomState(42)
        ow_models_set = set(OW_MODELS_ORDER)
        ow_models = sorted({r["model"] for r in unified if r["model"] in ow_models_set})
        for _ in range(2000):
            idx = rs.randint(0, len(ow_models), size=len(ow_models))
            sample_models = [ow_models[i] for i in idx]
            sm: dict[str, float] = {}
            for s in ("External", "History", "Icl", "Rag", "Tool"):
                vals = [r["disc_delta"] for r in unified
                        if r.get("suite") == s
                        and r["model"] in sample_models
                        and r.get("disc_delta") is not None]
                if vals:
                    sm[s] = float(np.mean(vals))
            if len(sm) > 1:
                arr = np.array(list(sm.values()))
                rng_boots.append(float(arr.max() - arr.min()))
        if rng_boots:
            rng_lo = float(np.percentile(rng_boots, 2.5))
            rng_hi = float(np.percentile(rng_boots, 97.5))
        else:
            rng_lo = rng_hi = float("nan")
    else:
        rng_mean = float("nan")
        rng_lo = rng_hi = float("nan")

    pts = [(r.get("acc10_control"), r.get("disc_delta"))
           for r in unified
           if r.get("acc10_control") is not None
           and r.get("disc_delta") is not None]
    xs = np.array([p[0] for p in pts])
    ys = np.array([p[1] for p in pts])
    r_pearson = float(np.corrcoef(xs, ys)[0, 1])
    rs2 = np.random.RandomState(42)
    boots = []
    for _ in range(2000):
        idx = rs2.randint(0, len(pts), size=len(pts))
        boots.append(float(np.corrcoef(xs[idx], ys[idx])[0, 1]))
    r_lo, r_hi = float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Contrast} & \\textbf{Est.} &")
    lines.append("    \\multicolumn{1}{c}{\\textbf{95\\% CI}} &")
    lines.append("    \\textbf{$p_{\\mathrm{BH}}$} \\\\")
    lines.append("    \\midrule")
    lines.append("    \\multicolumn{4}{@{}l}{\\emph{Plausible $>$ irrelevant} (mean $\\Delta$UAI)} \\\\")
    for (suite, m, lo, hi, _), p_adj in zip(suite_rows, bh_full):
        lo_s = fmt_num(lo, 2)
        hi_s = fmt_num(hi, 2)
        lines.append(
            f"    \\quad {SUITE_LATEX[suite]:<14} & {m:.2f} & "
            f"[{lo_s}, {hi_s}] & {fmt_p(p_adj)} \\\\"
        )
    lines.append("    \\midrule")
    lines.append(
        f"    Suite-mean Disc$_{{\\Delta}}$ range (open-weight panel)"
        f"    & {rng_mean:.2f} & [{rng_lo:.2f}, {rng_hi:.2f}] & --- \\\\"
    )
    r_p_s = fmt_num(r_pearson, 2)
    r_lo_s = fmt_num(r_lo, 2)
    r_hi_s = fmt_num(r_hi, 2)
    lines.append(
        f"    Pearson $r$(Acc, Disc$_{{\\Delta}}$)"
        f"    & {r_p_s} & [{r_lo_s}, {r_hi_s}] & --- \\\\"
    )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Statistical summary.")
    lines.append("    Top: Wilcoxon signed-rank tests for")
    lines.append("    UAI$_{\\text{pls}} > \\text{UAI}_{\\text{irr}}$")
    lines.append("    (BH-corrected $p$).")
    lines.append("    Bottom: cross-suite discrimination range and")
    lines.append("    Acc--Disc correlation. All CIs are bootstrap 95\\%.}")
    lines.append("  \\label{tab:stats_inference}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 11: tab:uai_distribution
# ---------------------------------------------------------------------------

def collect_pooled_uai(records_root: Path, baseline: str = "control",
                       suites: list[str] | None = None) -> dict[str, list[float]]:
    """Pool per-item UAI across all (model, suite) result files."""
    suites = suites or ["external", "history", "icl", "rag", "tool"]
    pooled: dict[str, list[float]] = {"irr": [], "plaus": []}
    for suite in suites:
        suite_dir = records_root / suite
        if not suite_dir.is_dir():
            continue
        for model_dir in sorted(suite_dir.iterdir()):
            if not model_dir.is_dir():
                continue
            rpath = model_dir / "results.jsonl"
            if not rpath.exists():
                continue
            recs = load_records(str(rpath))
            conds = {r.get("condition") for r in recs}
            bc = "control_twostage" if "control_twostage" in conds and "control" not in conds else "control"
            items = group_by_item(recs)
            for _iid, by_cond in items.items():
                ctrl = by_cond.get(bc)
                if ctrl is None:
                    continue
                y_ctrl = ctrl.get("answer_int")
                if y_ctrl is None:
                    continue
                for cond in ("irrelevant_low", "irrelevant_high",
                             "plausible_low", "plausible_high"):
                    rec = by_cond.get(cond)
                    if rec is None:
                        continue
                    y_a = rec.get("answer_int")
                    a = rec.get("anchor_value")
                    if y_a is None or a is None:
                        continue
                    denom = a - y_ctrl
                    if abs(denom) < 3.0:
                        continue
                    uai = (y_a - y_ctrl) / denom
                    if "irrelevant" in cond:
                        pooled["irr"].append(uai)
                    else:
                        pooled["plaus"].append(uai)
    return pooled


def build_uai_distribution(records_dirs: list[Path]) -> str:
    pooled: dict[str, list[float]] = {"irr": [], "plaus": []}
    for d in records_dirs:
        contribution = collect_pooled_uai(d)
        pooled["irr"].extend(contribution["irr"])
        pooled["plaus"].extend(contribution["plaus"])

    def stats(vals: list[float]) -> dict[str, float]:
        a = np.asarray(vals, dtype=float)
        return {
            "n": len(a),
            "in01": float(np.mean((a >= 0) & (a <= 1))),
            "over": float(np.mean(a > 1)),
            "rev": float(np.mean(a < 0)),
            "mean": float(a.mean()),
            "median": float(np.median(a)),
            "cap_mean": float(np.clip(a, 0, 1).mean()),
            "p5": float(np.percentile(a, 5)),
            "p25": float(np.percentile(a, 25)),
            "p75": float(np.percentile(a, 75)),
            "p95": float(np.percentile(a, 95)),
        }

    irr = stats(pooled["irr"])
    pls = stats(pooled["plaus"])

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lrr@{}}")
    lines.append("    \\toprule")
    lines.append("    & \\textbf{UAI\\textsubscript{irr}} & \\textbf{UAI\\textsubscript{pls}} \\\\")
    lines.append("    \\midrule")
    lines.append(f"    In $[0,1]$       & {irr['in01']*100:.1f}\\% & {pls['in01']*100:.1f}\\% \\\\")
    lines.append(f"    Overshoot ($>1$)  & {irr['over']*100:.1f}\\%  & {pls['over']*100:.1f}\\%  \\\\")
    lines.append(f"    Reverse ($<0$)    & {irr['rev']*100:.1f}\\% & {pls['rev']*100:.1f}\\% \\\\")
    lines.append("    \\midrule")
    lines.append(f"    Mean              & {irr['mean']:.2f}   & {pls['mean']:.2f}   \\\\")
    lines.append(f"    Median            & {irr['median']:.2f}   & {pls['median']:.2f}   \\\\")
    lines.append(f"    Capped $[0,1]$ mean & {irr['cap_mean']:.2f} & {pls['cap_mean']:.2f}   \\\\")
    lines.append("    \\midrule")
    lines.append(f"    5th pctl          & {fmt_num(irr['p5'], 2)} & {fmt_num(pls['p5'], 2)} \\\\")
    lines.append(f"    25th pctl         & {irr['p25']:.2f}    & {pls['p25']:.2f}   \\\\")
    lines.append(f"    75th pctl         & {irr['p75']:.2f}    & {pls['p75']:.2f}   \\\\")
    lines.append(f"    95th pctl         & {irr['p95']:.2f}    & {pls['p95']:.2f}   \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Distribution of per-item UAI values across all")
    lines.append(f"    models and suites ($n_{{\\text{{irr}}}}={irr['n']}$, "
                 f"$n_{{\\text{{pls}}}}={pls['n']}$).}}")
    lines.append("  \\label{tab:uai_distribution}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 12: tab:anchored_mae
# ---------------------------------------------------------------------------

def compute_delta_mae_by_suite(records_dirs: list[Path]) -> dict[str, dict[str, float]]:
    """Mean Delta-MAE by suite and relevance, averaged across models."""
    out: dict[str, dict[str, list[float]]] = {}
    for base in records_dirs:
        for suite in ("external", "history", "icl", "rag", "tool"):
            suite_dir = base / suite
            if not suite_dir.is_dir():
                continue
            for model_dir in sorted(suite_dir.iterdir()):
                if not model_dir.is_dir():
                    continue
                rpath = model_dir / "results.jsonl"
                if not rpath.exists():
                    continue
                recs = load_records(str(rpath))
                if not recs:
                    continue
                conds = {r.get("condition") for r in recs}
                bc = "control_twostage" if "control_twostage" in conds and "control" not in conds else "control"
                items = group_by_item(recs)
                mae_ctrl: list[float] = []
                mae_irr: list[float] = []
                mae_pls: list[float] = []
                for _iid, by_cond in items.items():
                    ctrl = by_cond.get(bc)
                    if ctrl is None:
                        continue
                    y_star = ctrl.get("y_star_evidence")
                    y_c = ctrl.get("answer_int")
                    if y_star is None or y_c is None:
                        continue
                    mae_ctrl.append(abs(y_c - y_star))
                    for cond in ("irrelevant_low", "irrelevant_high"):
                        rec = by_cond.get(cond)
                        if rec is None:
                            continue
                        y_a = rec.get("answer_int")
                        if y_a is None:
                            continue
                        mae_irr.append(abs(y_a - y_star))
                    for cond in ("plausible_low", "plausible_high"):
                        rec = by_cond.get(cond)
                        if rec is None:
                            continue
                        y_a = rec.get("answer_int")
                        if y_a is None:
                            continue
                        mae_pls.append(abs(y_a - y_star))
                if not mae_ctrl:
                    continue
                m_ctrl = float(np.mean(mae_ctrl))
                d_irr = float(np.mean(mae_irr) - m_ctrl) if mae_irr else None
                d_pls = float(np.mean(mae_pls) - m_ctrl) if mae_pls else None
                bucket = out.setdefault(suite, {"irr": [], "pls": []})
                if d_irr is not None:
                    bucket["irr"].append(d_irr)
                if d_pls is not None:
                    bucket["pls"].append(d_pls)
    summary: dict[str, dict[str, float]] = {}
    for suite, b in out.items():
        summary[suite] = {
            "irr": float(np.mean(b["irr"])) if b["irr"] else float("nan"),
            "pls": float(np.mean(b["pls"])) if b["pls"] else float("nan"),
        }
    return summary


def build_anchored_mae(delta: dict[str, dict[str, float]]) -> str:
    suite_to_key = {
        "External": "external", "History": "history", "Icl": "icl",
        "Rag": "rag", "Tool": "tool",
    }
    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Suite}")
    lines.append("    & \\textbf{$\\Delta$MAE\\textsubscript{irr}}")
    lines.append("    & \\textbf{$\\Delta$MAE\\textsubscript{pls}} \\\\")
    lines.append("    \\midrule")
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        key = suite_to_key[suite]
        d = delta.get(key, {})
        irr = d.get("irr")
        pls = d.get("pls")
        irr_s = f"$+${irr:.2f}" if irr is not None and irr >= 0 else (
            f"$-${abs(irr):.2f}" if irr is not None else "---"
        )
        pls_s = f"$+${pls:.2f}" if pls is not None and pls >= 0 else (
            f"$-${abs(pls):.2f}" if pls is not None else "---"
        )
        lines.append(f"    {SUITE_LATEX[suite]:<14} & {irr_s} & {pls_s} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Mean change in MAE from control to anchored")
    lines.append("    conditions (averaged across all models per suite).")
    lines.append("    Positive values indicate accuracy degradation.}")
    lines.append("  \\label{tab:anchored_mae}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 13: tab:history_matched (placeholder when matched-control data exists)
# ---------------------------------------------------------------------------

def build_history_matched(history_root: Path) -> str:
    """Build matched-control comparison table from a history run that includes
    both ``control`` and ``control_twostage`` conditions.

    The expected layout is ``history_root/<model_slug>/results.jsonl`` with both
    baseline conditions present in the same run.
    """
    rows: list[tuple[str, float, float, float, float]] = []
    for model in OW_MODELS_ORDER:
        slug = next((s for s in (
            "Qwen_Qwen2.5-1.5B-Instruct", "Qwen_Qwen2.5-3B-Instruct",
            "Qwen_Qwen2.5-7B-Instruct",
            "meta-llama_Llama-3.2-1B-Instruct",
            "meta-llama_Llama-3.2-3B-Instruct",
            "meta-llama_Llama-3.1-8B-Instruct",
            "google_gemma-3-1b-it", "google_gemma-3-4b-it",
            "allenai_OLMo-2-1124-13B-Instruct",
            "allenai_OLMo-2-0325-32B-Instruct",
        ) if model == _slug_to_short_safe(s)), None)
        if slug is None:
            continue
        rpath = history_root / slug / "results.jsonl"
        if not rpath.exists():
            continue
        recs = load_records(str(rpath))
        conds = {r.get("condition") for r in recs}
        if "control_twostage" not in conds:
            continue
        m_std = compute_unified_metrics(recs, baseline_condition="control")
        m_ts = compute_unified_metrics(recs, baseline_condition="control_twostage")
        rows.append((
            model,
            m_std.get("mae_control") or float("nan"),
            m_ts.get("mae_control") or float("nan"),
            m_std.get("disc_delta") or float("nan"),
            m_ts.get("disc_delta") or float("nan"),
        ))

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\tablestartstriped{3}")
    lines.append("  \\begin{tabular}{@{}lrrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Model}")
    lines.append("    & \\textbf{MAE\\textsubscript{std}}")
    lines.append("    & \\textbf{MAE\\textsubscript{ts}}")
    lines.append("    & \\textbf{Disc\\textsubscript{std}}")
    lines.append("    & \\textbf{Disc\\textsubscript{match}} \\\\")
    lines.append("    \\midrule")
    if not rows:
        lines.append("    \\multicolumn{5}{c}{No matched-control history run "
                     "found (need ``control'' + ``control\\_twostage'' "
                     "conditions in same results.jsonl).} \\\\")
    else:
        for model, mae_s, mae_t, d_s, d_m in rows:
            lines.append(
                f"    {short_to_latex(model):<16} & {mae_s:.2f}  & {mae_t:.2f} & "
                f"{fmt_num(d_s, 2)} & {fmt_num(d_m, 2)} \\\\"
            )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\tablestopstriped")
    lines.append("  \\caption{History suite: standard vs.\\ matched-format")
    lines.append("    (two-stage) control analysis.}")
    lines.append("  \\label{tab:history_matched}")
    lines.append("  \\label{tab:history_dual}")
    lines.append("\\end{table}")
    return "\n".join(lines)


def _slug_to_short_safe(slug: str) -> str:
    from anchorbench.eval.constants import MODEL_SHORT
    return MODEL_SHORT.get(slug, slug)


# ---------------------------------------------------------------------------
# Table 14: tab:icl_dist (ICL-metadata vs ICL-dist)
# ---------------------------------------------------------------------------

def build_icl_dist(unified: list[dict], icl_dist_metrics: list[dict]) -> str:
    by_model_std = {r["model"]: r for r in unified if r.get("suite") == "Icl"}
    by_model_dist = {r["model"]: r for r in icl_dist_metrics}

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\tablestartstriped{3}")
    lines.append("  \\begin{tabular}{@{}lrrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Model}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls,std}}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls,dist}}")
    lines.append("    & \\textbf{Disc\\textsubscript{std}}")
    lines.append("    & \\textbf{Disc\\textsubscript{dist}} \\\\")
    lines.append("    \\midrule")
    for model in OW_MODELS_ORDER:
        s = by_model_std.get(model)
        d = by_model_dist.get(model)
        if s is None and d is None:
            continue
        ups = fmt_num(s.get("uai_plaus") if s else None, 2)
        upd = fmt_num(d.get("uai_plaus") if d else None, 2)
        ds_ = fmt_num(s.get("disc_delta") if s else None, 2)
        dd_ = fmt_num(d.get("disc_delta") if d else None, 2)
        lines.append(
            f"    {short_to_latex(model):<16} & {ups} & {upd} & {ds_} & {dd_} \\\\"
        )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\tablestopstriped")
    lines.append("  \\caption{Standard ICL (metadata anchors) vs.\\ ICL-dist")
    lines.append("    (numerically relevant demonstrations).}")
    lines.append("  \\label{tab:icl_dist}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 15: tab:tool_plaintext
# ---------------------------------------------------------------------------

def build_tool_plaintext(unified: list[dict],
                         plaintext_metrics: list[dict] | None) -> str:
    structured_models = ["Qwen-1.5B", "Qwen-3B", "Qwen-7B",
                         "Llama-3B", "Llama-8B"]
    by_struct = {r["model"]: r for r in unified if r.get("suite") == "Tool"}
    by_plain: dict[str, dict] = {r["model"]: r
                                  for r in (plaintext_metrics or [])}

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\tablestartstriped{3}")
    lines.append("  \\begin{tabular}{@{}lrrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Model}")
    lines.append("    & \\textbf{Disc\\textsubscript{struct}}")
    lines.append("    & \\textbf{Disc\\textsubscript{plain}}")
    lines.append("    & \\textbf{MAE\\textsubscript{struct}}")
    lines.append("    & \\textbf{MAE\\textsubscript{plain}} \\\\")
    lines.append("    \\midrule")
    for model in structured_models:
        s = by_struct.get(model)
        p = by_plain.get(model)
        d_s = fmt_num(s.get("disc_delta") if s else None, 2)
        d_p = fmt_num(p.get("disc_delta") if p else None, 2)
        m_s = fmt_num(s.get("mae_control") if s else None, 2)
        m_p = fmt_num(p.get("mae_control") if p else None, 2)
        lines.append(
            f"    {short_to_latex(model):<16} & {d_s}  & {d_p}  & {m_s} & {m_p} \\\\"
        )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\tablestopstriped")
    lines.append("  \\caption{Tool suite: structured (\\texttt{role:~\"tool\"}) vs.\\")
    lines.append("    plaintext format. Disc: Disc$_{\\Delta}$;")
    lines.append("    MAE: control-condition MAE.}")
    lines.append("  \\label{tab:tool_plaintext}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 16: tab:difficulty
# ---------------------------------------------------------------------------

def compute_difficulty_table(unified: list[dict]) -> dict[str, dict[str, dict[str, float]]]:
    """Aggregate by_difficulty across models per suite."""
    out: dict[str, dict[str, dict[str, list[float]]]] = {}
    for r in unified:
        suite = r.get("suite")
        bd = r.get("by_difficulty", {})
        for diff, m in bd.items():
            bucket = out.setdefault(suite, {}).setdefault(
                diff, {"acc": [], "mae": [], "uai_irr": [],
                       "uai_plaus": [], "disc": []}
            )
            if m.get("acc10_control") is not None:
                bucket["acc"].append(m["acc10_control"])
            if m.get("mae_control") is not None:
                bucket["mae"].append(m["mae_control"])
            if m.get("uai_irr") is not None:
                bucket["uai_irr"].append(m["uai_irr"])
            if m.get("uai_plaus") is not None:
                bucket["uai_plaus"].append(m["uai_plaus"])
            if m.get("disc_delta") is not None:
                bucket["disc"].append(m["disc_delta"])
    summary: dict[str, dict[str, dict[str, float]]] = {}
    for suite, by_diff in out.items():
        summary[suite] = {}
        for diff, vals in by_diff.items():
            summary[suite][diff] = {k: (float(np.mean(v)) if v else float("nan"))
                                    for k, v in vals.items()}
    return summary


def build_difficulty(unified: list[dict]) -> str:
    summary = compute_difficulty_table(unified)
    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\setlength{\\tabcolsep}{3.5pt}")
    lines.append("  \\begin{tabular}{@{}llrrrrr@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Suite} & \\textbf{Diff.}")
    lines.append("    & \\textbf{Acc$_{10}$}")
    lines.append("    & \\textbf{MAE\\textsubscript{c}}")
    lines.append("    & \\textbf{UAI\\textsubscript{irr}}")
    lines.append("    & \\textbf{UAI\\textsubscript{pls}}")
    lines.append("    & \\textbf{Disc$_{\\Delta}$} \\\\")
    lines.append("    \\midrule")

    overall_easy = {"acc": [], "mae": [], "uai_irr": [], "uai_plaus": [], "disc": []}
    overall_hard = {"acc": [], "mae": [], "uai_irr": [], "uai_plaus": [], "disc": []}
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        s = summary.get(suite, {})
        easy = s.get("easy", {})
        hard = s.get("hard", {})
        if easy:
            for k in overall_easy:
                if k in easy and not np.isnan(easy[k]):
                    overall_easy[k].append(easy[k])
        if hard:
            for k in overall_hard:
                if k in hard and not np.isnan(hard[k]):
                    overall_hard[k].append(hard[k])

        e_disc = easy.get("disc", float("nan"))
        h_disc = hard.get("disc", float("nan"))
        bold_e = (not np.isnan(e_disc) and not np.isnan(h_disc)
                  and e_disc >= h_disc)
        bold_h = (not np.isnan(e_disc) and not np.isnan(h_disc)
                  and h_disc > e_disc)
        e_disc_s = (f"\\textbf{{{e_disc:.2f}}}" if bold_e
                    else fmt_num(e_disc, 2))
        h_disc_s = (f"\\textbf{{{h_disc:.2f}}}" if bold_h
                    else fmt_num(h_disc, 2))
        lines.append(
            f"    {SUITE_LATEX[suite]:<14} & easy & "
            f"{fmt_pct1(easy.get('acc'))} & {easy.get('mae', float('nan')):.1f} & "
            f"{fmt_num(easy.get('uai_irr'), 2)} & {fmt_num(easy.get('uai_plaus'), 2)} & {e_disc_s} \\\\"
        )
        lines.append(
            f"    & hard & {fmt_pct1(hard.get('acc'))} & {hard.get('mae', float('nan')):.1f} & "
            f"{fmt_num(hard.get('uai_irr'), 2)} & {fmt_num(hard.get('uai_plaus'), 2)} & {h_disc_s} \\\\"
        )

    def m(d: dict, k: str) -> float:
        return float(np.mean(d[k])) if d[k] else float("nan")

    lines.append("    \\midrule")
    e_disc_a = m(overall_easy, 'disc')
    h_disc_a = m(overall_hard, 'disc')
    bold_e = e_disc_a >= h_disc_a
    e_disc_a_s = f"\\textbf{{{e_disc_a:.2f}}}" if bold_e else fmt_num(e_disc_a, 2)
    h_disc_a_s = fmt_num(h_disc_a, 2) if bold_e else f"\\textbf{{{h_disc_a:.2f}}}"
    lines.append(
        f"    \\textit{{All}}   & easy & --- & --- & "
        f"{fmt_num(m(overall_easy, 'uai_irr'), 2)} & {fmt_num(m(overall_easy, 'uai_plaus'), 2)} & {e_disc_a_s} \\\\"
    )
    lines.append(
        f"    & hard & --- & --- & "
        f"{fmt_num(m(overall_hard, 'uai_irr'), 2)} & {fmt_num(m(overall_hard, 'uai_plaus'), 2)} & {h_disc_a_s} \\\\"
    )
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("  \\caption{Anchoring metrics by item difficulty")
    lines.append("    (mean across models per suite).}")
    lines.append("  \\label{tab:difficulty}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Boundary clipping subtable
# ---------------------------------------------------------------------------

def build_boundary(records_dirs: list[Path]) -> str:
    """Compute UAI_pls at delta in {15, 25, 40} on External + RAG, with and
    without items where the anchor is clipped to {0, 100}.
    """
    suites = ["external", "rag"]
    all_uai: dict[int, list[float]] = {15: [], 25: [], 40: []}
    excl_uai: dict[int, list[float]] = {15: [], 25: [], 40: []}
    for base in records_dirs:
        for suite in suites:
            suite_dir = base / suite
            if not suite_dir.is_dir():
                continue
            for model_dir in sorted(suite_dir.iterdir()):
                if not model_dir.is_dir():
                    continue
                rpath = model_dir / "results.jsonl"
                if not rpath.exists():
                    continue
                recs = load_records(str(rpath))
                items = group_by_item(recs)
                for iid, by_cond in items.items():
                    ctrl = by_cond.get("control")
                    if ctrl is None:
                        continue
                    y_c = ctrl.get("answer_int")
                    if y_c is None:
                        continue
                    for cond in ("plausible_low", "plausible_high"):
                        rec = by_cond.get(cond)
                        if rec is None:
                            continue
                        y_a = rec.get("answer_int")
                        a = rec.get("anchor_value")
                        if y_a is None or a is None:
                            continue
                        denom = a - y_c
                        if abs(denom) < 3.0:
                            continue
                        uai = (y_a - y_c) / denom
                        offset = None
                        anchors = rec.get("anchors")
                        if isinstance(anchors, dict):
                            offset = anchors.get("offset")
                        if offset is None:
                            offset = rec.get("anchor_offset")
                        if offset is None:
                            import re
                            m = re.search(r"-off(\d+)-", iid or "")
                            if m:
                                offset = int(m.group(1))
                        if offset is None or int(offset) not in (15, 25, 40):
                            continue
                        offset = int(offset)
                        all_uai[offset].append(uai)
                        if a not in (0, 100):
                            excl_uai[offset].append(uai)

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix")
    lines.append("\\begin{center}")
    lines.append("  \\small")
    lines.append("  \\begin{tabular}{@{}lccc@{}}")
    lines.append("    \\toprule")
    lines.append("    & $\\delta{=}15$ & $\\delta{=}25$ & $\\delta{=}40$ \\\\")
    lines.append("    \\midrule")
    means_all = [float(np.mean(all_uai[d])) if all_uai[d] else float("nan") for d in (15, 25, 40)]
    means_excl = [float(np.mean(excl_uai[d])) if excl_uai[d] else float("nan") for d in (15, 25, 40)]
    lines.append(f"    All items           & {means_all[0]:.2f} & {means_all[1]:.2f} & {means_all[2]:.2f} \\\\")
    lines.append(f"    Excl.\\ boundary     & {means_excl[0]:.2f} & {means_excl[1]:.2f} & {means_excl[2]:.2f} \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append("\\end{center}")
    n_all_40 = len(all_uai[40])
    n_excl_40 = len(excl_uai[40])
    n_clipped = n_all_40 - n_excl_40
    lines.append(f"% Boundary clipping affects {n_clipped}/{n_all_40} "
                 f"({100*n_clipped/max(n_all_40,1):.1f}%) items at delta=40.")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# tab:model-details (model panel from anchorbench.eval.constants)
# ---------------------------------------------------------------------------

PARAM_BY_SLUG = {
    "Qwen/Qwen2.5-1.5B-Instruct": "1.5B",
    "Qwen/Qwen2.5-3B-Instruct": "3B",
    "Qwen/Qwen2.5-7B-Instruct": "7B",
    "meta-llama/Llama-3.2-1B-Instruct": "1B",
    "meta-llama/Llama-3.2-3B-Instruct": "3B",
    "meta-llama/Llama-3.1-8B-Instruct": "8B",
    "google/gemma-3-1b-it": "1B",
    "google/gemma-3-4b-it": "4B",
    "allenai/OLMo-2-1124-13B-Instruct": "13B",
    "allenai/OLMo-2-0325-32B-Instruct": "32B",
}

FAMILY_MACRO = {
    "Qwen/Qwen2.5-1.5B-Instruct": r"\qwen",
    "Qwen/Qwen2.5-3B-Instruct": r"\qwen",
    "Qwen/Qwen2.5-7B-Instruct": r"\qwen",
    "meta-llama/Llama-3.2-1B-Instruct": r"\llama",
    "meta-llama/Llama-3.2-3B-Instruct": r"\llama",
    "meta-llama/Llama-3.1-8B-Instruct": r"\llama",
    "google/gemma-3-1b-it": r"\gemma",
    "google/gemma-3-4b-it": r"\gemma",
    "allenai/OLMo-2-1124-13B-Instruct": r"\aitwo",
    "allenai/OLMo-2-0325-32B-Instruct": r"\aitwo",
    "openai/gpt-5.4-mini": r"\openai",
    "anthropic/claude-haiku-4.5": r"\claude",
    "google/gemini-2.5-flash": r"\gemini",
    "x-ai/grok-3-mini-beta": r"\grok",
}


def build_model_details(ow: list[str] | None = None,
                        api: list[str] | None = None) -> str:
    """Render tab:model-details for the 14-model panel.

    The model panel is sourced from :mod:`anchorbench.eval.constants`, which
    ships inside the package. It used to be read from a ``configs/benchmark.yaml``
    that no longer exists; that file only ever held the same two lists, and the
    params/family-macro mappings below were already duplicated here.
    """
    if ow is None:
        ow = list(OW_MODEL_IDS)
    if api is None:
        api = list(API_MODEL_IDS)

    lines: list[str] = []
    lines.append("% Auto-generated by anchorbench.paper.tables_appendix"
                 " from anchorbench.eval.constants")
    lines.append("\\begin{table}[ht]")
    lines.append("  \\centering")
    lines.append("  \\small")
    lines.append("  \\setlength{\\tabcolsep}{4pt}")
    lines.append("  \\begin{tabularx}{\\textwidth}{@{}Xccc@{}}")
    lines.append("    \\toprule")
    lines.append("    \\textbf{Model card} & \\textbf{Params} & \\textbf{Access} & \\textbf{Route} \\\\")
    lines.append("    \\midrule")
    for slug in ow:
        macro = FAMILY_MACRO.get(slug, "")
        params = PARAM_BY_SLUG.get(slug, "---")
        lines.append(f"    {macro}~\\path{{{slug}}} & {params} & Open-weight & Local \\\\")
    for slug in api:
        macro = FAMILY_MACRO.get(slug, "")
        lines.append(f"    {macro}~\\path{{{slug}}} & --- & API & OpenRouter \\\\")
    lines.append("    \\bottomrule")
    lines.append("  \\end{tabularx}")
    lines.append("  \\caption{Model panel used in \\textsc{AnchorBench}.")
    lines.append("    Open-weight models were served locally on H100 GPUs;")
    lines.append("    API models were accessed through OpenRouter.}")
    lines.append("  \\label{tab:model-details}")
    lines.append("\\end{table}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers for compute-on-the-fly summaries
# ---------------------------------------------------------------------------

def compute_unified_for_dir(records_dir: Path, suite: str | None = None) -> list[dict]:
    """Compute unified metrics for every results.jsonl under records_dir.

    Layout 1: ``records_dir/<suite>/<model_slug>/results.jsonl``
    Layout 2: ``records_dir/<model_slug>/results.jsonl`` (single suite)
    """
    out: list[dict] = []
    if any((p / "results.jsonl").exists() for p in records_dir.glob("*/")
           if p.is_dir()):
        for short, slug, path in discover_jsonl(records_dir.parent,
                                                records_dir.name):
            recs = load_records(str(path))
            if not recs:
                continue
            conds = {r.get("condition") for r in recs}
            bc = "control_twostage" if "control_twostage" in conds and "control" not in conds else "control"
            m = compute_unified_metrics(recs, baseline_condition=bc)
            m["model"] = short
            m["model_slug"] = slug
            m["suite"] = suite or records_dir.name.capitalize()
            out.append(m)
    return out


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--ow_unified", type=Path,
                   default=DEFAULT_OW_RESULTS / "unified_all_suites.json")
    p.add_argument("--api_unified", type=Path,
                   default=DEFAULT_API_RESULTS / "unified_all_suites.json")
    p.add_argument("--ow_records", type=Path, default=DEFAULT_OW_RESULTS)
    p.add_argument("--api_records", type=Path, default=DEFAULT_API_RESULTS)
    p.add_argument("--icl_dist_ow", type=Path, default=DEFAULT_ICL_DIST_OW,
                   help="ICL-dist OW results dir (e.g. results/icl_dist_core/icl)")
    p.add_argument("--icl_dist_api", type=Path, default=DEFAULT_ICL_DIST_API,
                   help="ICL-dist API results dir (e.g. results/icl_dist_api)")
    p.add_argument("--history_matched", type=Path, default=None,
                   help="Optional dir containing history matched-control runs"
                        " (each <slug>/results.jsonl with both control + control_twostage).")
    p.add_argument("--tool_plaintext", type=Path, default=None,
                   help="Optional dir containing tool plaintext-format runs.")
    p.add_argument("--out_dir", type=Path, default=DEFAULT_TABLE_DIR)
    args = p.parse_args()

    with open(args.ow_unified) as f:
        ow = json.load(f)
    with open(args.api_unified) as f:
        api = json.load(f)
    unified = ow + api
    print(f"Loaded {len(unified)} model-suite cells")

    # Tables 4-8: per-suite full results
    captions = {
        "External": "\\externalsuite~suite full results (360~items, 1{,}800~prompts per model).",
        "History":  "\\historysuite~suite full results (360~items, two-stage protocol).",
        "Icl":      "\\iclsuite~suite full results (360~items).",
        "Rag":      "\\ragsuite~suite full results (360~items).",
        "Tool":     "\\toolsuite~suite full results (360~items).",
    }
    labels = {
        "External": "tab:app-external",
        "History":  "tab:app-history",
        "Icl":      "tab:app-icl",
        "Rag":      "tab:app-rag",
        "Tool":     "tab:app-tool",
    }
    file_keys = {
        "External": "external", "History": "history", "Icl": "icl",
        "Rag": "rag", "Tool": "tool",
    }
    for suite in ("External", "History", "Icl", "Rag", "Tool"):
        body = build_per_suite_table(unified, suite, labels[suite],
                                     captions[suite])
        write_table(args.out_dir / f"tab_app_{file_keys[suite]}.tex", body)

    # ICL-dist metrics (open-weight only by default per paper Table 14)
    icl_dist_ow_metrics: list[dict] = []
    if args.icl_dist_ow.is_dir():
        for slug_dir in sorted(args.icl_dist_ow.iterdir()):
            if not slug_dir.is_dir():
                continue
            rpath = slug_dir / "results.jsonl"
            if not rpath.exists():
                continue
            recs = load_records(str(rpath))
            if not recs:
                continue
            m = compute_unified_metrics(recs)
            m["model"] = _slug_to_short_safe(slug_dir.name)
            m["model_slug"] = slug_dir.name
            m["suite"] = "Icl-dist"
            icl_dist_ow_metrics.append(m)

    # Tables 9-16
    write_table(args.out_dir / "tab_uai_summary.tex",
                build_uai_summary(unified, icl_dist_ow_metrics))
    write_table(args.out_dir / "tab_stats_inference.tex",
                build_stats_inference(unified))
    write_table(args.out_dir / "tab_uai_distribution.tex",
                build_uai_distribution([args.ow_records, args.api_records]))
    delta_mae = compute_delta_mae_by_suite([args.ow_records, args.api_records])
    write_table(args.out_dir / "tab_anchored_mae.tex",
                build_anchored_mae(delta_mae))
    write_table(args.out_dir / "tab_history_matched.tex",
                build_history_matched(args.history_matched
                                      or args.ow_records / "history"))
    write_table(args.out_dir / "tab_icl_dist.tex",
                build_icl_dist(unified, icl_dist_ow_metrics))

    plaintext_metrics: list[dict] = []
    if args.tool_plaintext and args.tool_plaintext.is_dir():
        for slug_dir in sorted(args.tool_plaintext.iterdir()):
            if not slug_dir.is_dir():
                continue
            rpath = slug_dir / "results.jsonl"
            if not rpath.exists():
                continue
            recs = load_records(str(rpath))
            if not recs:
                continue
            m = compute_unified_metrics(recs)
            m["model"] = _slug_to_short_safe(slug_dir.name)
            plaintext_metrics.append(m)
    write_table(args.out_dir / "tab_tool_plaintext.tex",
                build_tool_plaintext(unified, plaintext_metrics))

    write_table(args.out_dir / "tab_difficulty.tex", build_difficulty(unified))
    write_table(args.out_dir / "tab_boundary.tex",
                build_boundary([args.ow_records, args.api_records]))
    write_table(args.out_dir / "tab_model_details.tex",
                build_model_details())

    print("\nDone. Tables written to:", args.out_dir)


if __name__ == "__main__":
    main()
