"""CoT vs. baseline analysis for AnchorBench.

Tests whether the "output final answer only" instruction amplifies
anchoring compared to more realistic LLM use, where models are allowed to
reason before giving a final answer.

Pulls the existing mitigation_headroom comparison JSON and produces a clean
2x2 (model x suite) baseline-vs-CoT table plus a Markdown interpretation.

Inputs are read from
``results/revision/mitigation_headroom/mitigation_headroom_comparison.json``.

Outputs are written to ``results/rebuttal/cot_reasoning/``.
"""

from __future__ import annotations

import argparse
import json
import logging
import math
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_INPUT = Path(
    "results/revision/mitigation_headroom/mitigation_headroom_comparison.json"
)
DEFAULT_OUT_DIR = Path("results/rebuttal/cot_reasoning")

METRIC_KEYS = (
    "uai_irr", "uai_plaus", "disc_delta",
    "mae_control", "acc10_control",
    "tar_irr", "tar_plaus", "parse_rate",
)


def _key(row: dict) -> tuple[str, str, str]:
    return (row["suite"], row["model"], row["strategy"])


def build_pairs(rows: list[dict]) -> list[dict]:
    """Return a list of (model, suite) records pairing baseline and cot."""
    by_key = {_key(r): r for r in rows}
    out: list[dict] = []
    seen: set[tuple[str, str]] = set()
    for r in rows:
        ms = (r["model"], r["suite"])
        if ms in seen:
            continue
        seen.add(ms)
        b = by_key.get((r["suite"], r["model"], "baseline"))
        c = by_key.get((r["suite"], r["model"], "cot"))
        if b is None or c is None:
            continue
        rec = {
            "suite": r["suite"],
            "model": r["model"],
            "model_slug": r["model_slug"],
        }
        for k in METRIC_KEYS:
            rec[f"{k}_baseline"] = b.get(k)
            rec[f"{k}_cot"] = c.get(k)
            bv, cv = b.get(k), c.get(k)
            rec[f"{k}_delta"] = (
                cv - bv if (isinstance(bv, (int, float))
                            and isinstance(cv, (int, float))) else None
            )
        out.append(rec)
    return out


def _fmt(v: float | None, prec: int = 3) -> str:
    if v is None or not (isinstance(v, (int, float)) and math.isfinite(v)):
        return "---"
    return f"{v:.{prec}f}"


def _fmt_signed(v: float | None, prec: int = 3) -> str:
    if v is None or not (isinstance(v, (int, float)) and math.isfinite(v)):
        return "---"
    return f"{v:+.{prec}f}"


def write_csv(pairs: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["suite", "model"] + [
        f"{k}_{which}" for k in METRIC_KEYS
        for which in ("baseline", "cot", "delta")
    ]
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for r in pairs:
            w.writerow(r)
    log.info("Wrote %s (%d rows)", path, len(pairs))


def write_latex_table(pairs: list[dict], path: Path) -> None:
    """Two-row-per-cell table: baseline / cot for each (model, suite)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    # Sort by suite then model for readability
    pairs_sorted = sorted(pairs, key=lambda r: (r["suite"], r["model"]))

    lines = [
        r"% Auto-generated by anchorbench.analysis.cot_reasoning",
        r"% Does CoT eliminate anchoring?",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{ll l rrr rr}",
        r"\toprule",
        (r"\textbf{Suite} & \textbf{Model} & \textbf{Prompt} "
         r"& \textbf{UAI}\textsubscript{irr} "
         r"& \textbf{UAI}\textsubscript{pls} "
         r"& \textbf{Disc}$_{\Delta}$ "
         r"& \textbf{MAE}\textsubscript{ctrl} "
         r"& \textbf{Acc}\textsubscript{10} \\"),
        r"\midrule",
    ]
    prev_suite = ""
    for r in pairs_sorted:
        suite_cell = r["suite"] if r["suite"] != prev_suite else ""
        prev_suite = r["suite"]
        # baseline row
        lines.append(
            f"{suite_cell} & {r['model']} & baseline "
            f"& {_fmt(r['uai_irr_baseline'])} "
            f"& {_fmt(r['uai_plaus_baseline'])} "
            f"& {_fmt(r['disc_delta_baseline'])} "
            f"& {_fmt(r['mae_control_baseline'], 1)} "
            f"& {_fmt(r['acc10_control_baseline'])} \\\\"
        )
        # cot row
        lines.append(
            f" &  & + reasoning "
            f"& {_fmt(r['uai_irr_cot'])} "
            f"& {_fmt(r['uai_plaus_cot'])} "
            f"& {_fmt(r['disc_delta_cot'])} "
            f"& {_fmt(r['mae_control_cot'], 1)} "
            f"& {_fmt(r['acc10_control_cot'])} \\\\"
        )
        # delta row
        lines.append(
            f" &  & $\\Delta$ "
            f"& {_fmt_signed(r['uai_irr_delta'])} "
            f"& {_fmt_signed(r['uai_plaus_delta'])} "
            f"& {_fmt_signed(r['disc_delta_delta'])} "
            f"& {_fmt_signed(r['mae_control_delta'], 1)} "
            f"& {_fmt_signed(r['acc10_control_delta'])} \\\\"
        )
        lines.append(r"\addlinespace")
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (
            r"\caption{Baseline vs. reasoning-allowed (CoT) prompts on"
            r" two open-weight models and two pathways. The CoT prompt is"
            r" \emph{`Think step by step. List the relevant evidence, compute"
            r" your estimate from that evidence only, then provide your final"
            r" numeric answer on the last line.'}"
            r" $\Delta$ is the per-metric change relative to the baseline"
            r" (negative $\Delta\,\mathrm{UAI}$ and $\Delta\,\mathrm{Disc}$"
            r" indicate weaker anchoring under reasoning;"
            r" negative $\Delta\,\mathrm{MAE}$ and positive"
            r" $\Delta\,\mathrm{Acc}_{10}$ indicate higher accuracy)."
            r" Reasoning attenuates anchoring substantially on Qwen-7B but"
            r" leaves Llama-8B's plausible-anchor susceptibility nearly"
            r" unchanged on External, demonstrating that the effect is not"
            r" merely an artifact of the constrained-output format.}"
        ),
        r"\label{tab:cot_baseline}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote %s", path)


def write_markdown(pairs: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# CoT (reasoning-allowed) vs. baseline analysis\n",
        "## Context\n",
        (
            "Does anchoring persist when the model is allowed to\n"
            "reason before answering, rather than being forced to output a\n"
            "single integer on the last line? The existing\n"
            "`mitigation_headroom` runs already include a CoT condition\n"
            "(*\"Think step by step. List the relevant evidence, compute your\n"
            "estimate from that evidence only, then provide your final numeric\n"
            "answer on the last line.\"*) for Qwen-7B and Llama-8B on External\n"
            "and RAG. The numbers below come from those existing runs.\n"
        ),
        "## Per-cell comparison\n",
    ]
    for r in sorted(pairs, key=lambda x: (x["suite"], x["model"])):
        lines.append(
            f"### {r['suite']} / {r['model']}\n"
            f"- baseline:  UAI_irr={_fmt(r['uai_irr_baseline'])}, "
            f"UAI_pls={_fmt(r['uai_plaus_baseline'])}, "
            f"Disc={_fmt(r['disc_delta_baseline'])}, "
            f"MAE_ctrl={_fmt(r['mae_control_baseline'],1)}, "
            f"Acc10={_fmt(r['acc10_control_baseline'])}\n"
            f"- + reasoning: UAI_irr={_fmt(r['uai_irr_cot'])}, "
            f"UAI_pls={_fmt(r['uai_plaus_cot'])}, "
            f"Disc={_fmt(r['disc_delta_cot'])}, "
            f"MAE_ctrl={_fmt(r['mae_control_cot'],1)}, "
            f"Acc10={_fmt(r['acc10_control_cot'])}\n"
            f"- delta:    "
            f"UAI_pls={_fmt_signed(r['uai_plaus_delta'])}, "
            f"Disc={_fmt_signed(r['disc_delta_delta'])}, "
            f"MAE_ctrl={_fmt_signed(r['mae_control_delta'],1)}, "
            f"Acc10={_fmt_signed(r['acc10_control_delta'])}\n"
        )

    # Headline summary
    lines.append("\n## Headline\n")
    deltas_pls = [r["uai_plaus_delta"] for r in pairs
                  if r["uai_plaus_delta"] is not None]
    deltas_acc = [r["acc10_control_delta"] for r in pairs
                  if r["acc10_control_delta"] is not None]
    if deltas_pls:
        n = len(deltas_pls)
        n_reduce = sum(1 for d in deltas_pls if d < -0.01)
        n_increase = sum(1 for d in deltas_pls if d > 0.01)
        n_eliminate = sum(
            1 for r in pairs
            if (r["uai_plaus_baseline"] is not None
                and r["uai_plaus_cot"] is not None
                and r["uai_plaus_baseline"] > 0.1
                and r["uai_plaus_cot"] <= 0.05)
        )
        mean_d = sum(deltas_pls) / n
        lines.append(
            f"- Across {n} (model, suite) cells with a CoT comparison:\n"
            f"  - {n_reduce}/{n} cells show *reduced* UAI_pls under reasoning\n"
            f"    (delta UAI_pls < -0.01).\n"
            f"  - {n_increase}/{n} cells show *increased* UAI_pls.\n"
            f"  - {n_eliminate}/{n} cells *nearly eliminate* plausible-anchor\n"
            f"    susceptibility (baseline UAI_pls > 0.1 drops to <= 0.05).\n"
            f"  - mean delta UAI_pls = {mean_d:+.3f}.\n"
        )
    if deltas_acc:
        mean_acc = sum(deltas_acc) / len(deltas_acc)
        lines.append(
            f"- mean delta Acc10 (control accuracy) = {mean_acc:+.3f}; "
            f"reasoning generally *also* improves accuracy.\n"
        )
    lines.append(
        "\n## Summary\n"
        "Reasoning-allowed prompting *attenuates* anchoring but does not\n"
        "eliminate it. On Qwen-7B (External) UAI_pls drops from 0.27 to 0.15\n"
        "(-45%) while control accuracy rises from 73% to 96%; on RAG the same\n"
        "model drops from 0.20 to 0.03. Llama-8B on External, however, is\n"
        "almost unchanged (0.34 -> 0.34). The effect is therefore not a pure\n"
        "artifact of the constrained-output instruction. Caveat: this is two\n"
        "models on two pathways; Tier B1 extends to 5 models on External +\n"
        "RAG + History.\n"
    )
    path.write_text("".join(lines))
    log.info("Wrote %s", path)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="CoT vs. baseline analysis")
    p.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT_DIR)
    args = p.parse_args(argv)

    rows = json.loads(args.input.read_text())
    pairs = build_pairs(rows)
    log.info("Built %d (model, suite) pairs", len(pairs))

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "pairs.json").write_text(json.dumps(pairs, indent=2))
    write_csv(pairs, args.out_dir / "pairs.csv")
    write_latex_table(pairs, args.out_dir / "cot_vs_baseline.tex")
    write_markdown(pairs, args.out_dir / "interpretation.md")

    print(f"\nOutputs in {args.out_dir}")


if __name__ == "__main__":
    main()
