"""Extended CoT analysis.

Walks the directory produced by ``anchorbench.runners.rebuttal_cot`` and the
API helper (`scripts/rebuttal/_b1_api_model.sh`), which both reshape outputs
into ``results/rebuttal/cot_extended/<suite>/<model_slug>/<strategy>/``, and
produces a 5-model x 3-suite baseline-vs-CoT comparison.

This complements ``cot_reasoning.py``, which used the 2-model x 2-suite
``mitigation_headroom_comparison.json``; this module covers the full
5-model panel including the History suite.

Outputs are written to ``results/rebuttal/cot_reasoning_extended/``.
"""

from __future__ import annotations

import argparse
import json
import logging
import math
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_IN_DIR = Path("results/rebuttal/cot_extended")
DEFAULT_OUT_DIR = Path("results/rebuttal/cot_reasoning_extended")

SUITES = ("external", "rag", "history")
STRATEGIES = ("baseline", "cot")
METRIC_KEYS = (
    "uai_irr", "uai_plaus", "disc_delta",
    "mae_control", "acc10_control", "parse_rate",
)


def _load_summary(p: Path) -> dict | None:
    if not p.exists():
        return None
    return json.loads(p.read_text())


def gather_pairs(in_dir: Path) -> list[dict]:
    """For every (suite, model) with both baseline and cot, return a paired row."""
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for suite in SUITES:
        suite_dir = in_dir / suite
        if not suite_dir.exists():
            continue
        for slug_dir in sorted(suite_dir.iterdir()):
            if not slug_dir.is_dir() or slug_dir.name.startswith("_"):
                continue
            slug = slug_dir.name
            b = _load_summary(slug_dir / "baseline" / "summary.json")
            c = _load_summary(slug_dir / "cot" / "summary.json")
            if not b or not c:
                log.warning("Skipping %s/%s: missing baseline or cot summary",
                            suite, slug)
                continue
            row = {
                "suite": suite,
                "model": MODEL_SHORT.get(slug, slug),
                "model_slug": slug,
            }
            for k in METRIC_KEYS:
                row[f"{k}_baseline"] = b.get(k)
                row[f"{k}_cot"] = c.get(k)
                bv = b.get(k)
                cv = c.get(k)
                row[f"{k}_delta"] = (
                    cv - bv if (isinstance(bv, (int, float))
                                and isinstance(cv, (int, float))) else None
                )
            rows.append(row)
    return rows


def _fmt(v: float | None, prec: int = 3) -> str:
    if v is None or not (isinstance(v, (int, float)) and math.isfinite(v)):
        return "---"
    return f"{v:.{prec}f}"


def _fmt_signed(v: float | None, prec: int = 3) -> str:
    if v is None or not (isinstance(v, (int, float)) and math.isfinite(v)):
        return "---"
    return f"{v:+.{prec}f}"


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        return
    keys = list(rows[0].keys())
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    log.info("Wrote %s (%d rows)", path, len(rows))


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))
    log.info("Wrote %s", path)


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows_sorted = sorted(rows, key=lambda r: (r["suite"], r["model"]))
    lines = [
        r"% Auto-generated by anchorbench.analysis.cot_reasoning_extended",
        r"% CoT extension on the 5-model panel.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{ll rrr rrr rrr}",
        r"\toprule",
        r"& & \multicolumn{3}{c}{UAI$_{\mathrm{irr}}$} "
        r"& \multicolumn{3}{c}{UAI$_{\mathrm{pls}}$} "
        r"& \multicolumn{3}{c}{Disc$_{\Delta}$} \\",
        r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}\cmidrule(lr){9-11}",
        r"Suite & Model & base & CoT & $\Delta$ & base & CoT & $\Delta$ "
        r"& base & CoT & $\Delta$ \\",
        r"\midrule",
    ]
    prev = ""
    for r in rows_sorted:
        suite = r["suite"] if r["suite"] != prev else ""
        prev = r["suite"]
        lines.append(
            f"{suite} & {r['model']} & "
            f"{_fmt(r['uai_irr_baseline'], 2)} & {_fmt(r['uai_irr_cot'], 2)} "
            f"& {_fmt_signed(r['uai_irr_delta'], 2)} & "
            f"{_fmt(r['uai_plaus_baseline'], 2)} & {_fmt(r['uai_plaus_cot'], 2)} "
            f"& {_fmt_signed(r['uai_plaus_delta'], 2)} & "
            f"{_fmt(r['disc_delta_baseline'], 2)} & {_fmt(r['disc_delta_cot'], 2)} "
            f"& {_fmt_signed(r['disc_delta_delta'], 2)} \\\\"
        )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (
            r"\caption{Reasoning-allowed (Chain-of-Thought) prompting"
            r" vs.\ ``final answer only'' baseline across the locked"
            r" 5-model panel and all three suites (External, RAG, History)."
            r" CoT lowers plausible-anchor influence in 11 of the 15"
            r" model--suite cells, but the effect is model- and"
            r" pathway-dependent rather than uniform: it lowers both"
            r" UAI$_{\mathrm{irr}}$ and UAI$_{\mathrm{pls}}$ in only 6"
            r" cells, and raises UAI$_{\mathrm{pls}}$ in 4."
            r" UAI$_{\mathrm{pls}}$ remains positive in 13 of 15 cells,"
            r" so anchoring is attenuated but not an artifact of the"
            r" answer-only protocol.}"
        ),
        r"\label{tab:cot_extended}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote %s", path)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    from collections import defaultdict
    by_suite: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_suite[r["suite"]].append(r)

    def _mean(rs: list[dict], key: str) -> float | None:
        vals = [r[key] for r in rs
                if r.get(key) is not None and isinstance(r[key], (int, float))]
        return sum(vals) / len(vals) if vals else None

    lines = [
        "# Reasoning-allowed CoT extension\n\n",
        f"Extended from 2 to {len(set(r['model'] for r in rows))} models "
        f"and from 2 suites to {len(by_suite)} suites (External, RAG, History).\n\n",
    ]
    for suite, rs in by_suite.items():
        lines.append(f"## {suite.capitalize()}\n\n")
        for key in ("uai_irr", "uai_plaus", "disc_delta"):
            bm = _mean(rs, f"{key}_baseline")
            cm = _mean(rs, f"{key}_cot")
            dm = _mean(rs, f"{key}_delta")
            if bm is not None and cm is not None:
                lines.append(
                    f"- mean {key}: baseline={bm:+.3f}, "
                    f"CoT={cm:+.3f}, \u0394={dm:+.3f}\n"
                )
        lines.append("\n")
        lines.append("| Model | UAI_pls base | UAI_pls CoT | \u0394 UAI_pls | "
                     "Disc base | Disc CoT | \u0394 Disc |\n")
        lines.append("|---|---:|---:|---:|---:|---:|---:|\n")
        for r in sorted(rs, key=lambda x: x["model"]):
            lines.append(
                f"| {r['model']} | "
                f"{_fmt(r['uai_plaus_baseline'], 2)} | "
                f"{_fmt(r['uai_plaus_cot'], 2)} | "
                f"{_fmt_signed(r['uai_plaus_delta'], 2)} | "
                f"{_fmt(r['disc_delta_baseline'], 2)} | "
                f"{_fmt(r['disc_delta_cot'], 2)} | "
                f"{_fmt_signed(r['disc_delta_delta'], 2)} |\n"
            )
        lines.append("\n")

    # Across-suite & across-model summary
    all_pls_delta = [r["uai_plaus_delta"] for r in rows
                     if r.get("uai_plaus_delta") is not None]
    n_pls_neg = sum(1 for d in all_pls_delta if d < 0)
    lines.append("## Summary\n\n")
    if all_pls_delta:
        lines.append(
            f"- CoT reduces UAI_pls in {n_pls_neg}/{len(all_pls_delta)} "
            f"(suite, model) cells\n"
            f"- mean \u0394UAI_pls (CoT - baseline) = "
            f"{sum(all_pls_delta)/len(all_pls_delta):+.3f}\n"
            f"- UAI_pls > 0 under CoT in "
            f"{sum(1 for r in rows if (r.get('uai_plaus_cot') or 0) > 0)}"
            f"/{len(rows)} cells (CoT mitigates but does NOT eliminate"
            f" anchoring).\n"
        )
    path.write_text("".join(lines))
    log.info("Wrote %s", path)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="Extended CoT analysis (B1)")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN_DIR)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT_DIR)
    args = p.parse_args(argv)

    rows = gather_pairs(args.in_dir)
    log.info("Gathered %d (suite, model) rows", len(rows))
    if not rows:
        log.error("No paired rows; aborting")
        raise SystemExit(1)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "pairs.csv")
    write_json(rows, args.out_dir / "pairs.json")
    write_latex(rows, args.out_dir / "cot_vs_baseline.tex")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
