"""Cross-pathway intensity analysis.

Reads ``results/rebuttal/intensity{,_rag,_history}/<slug>/intensity_curve.json``
for every model and emits:
  intensity_pathway.csv / .json
  intensity_pathway_table.tex (3-panel: External / RAG / History)
  intensity_pathway.pdf / .png (3-panel grouped curves)
  interpretation.md
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from anchorbench.analysis._io import fmt_latex, write_csv, write_json

log = logging.getLogger(__name__)

SUITES = ("external", "rag", "history")
SUITE_LABEL = {"external": "External", "rag": "RAG", "history": "History"}
INPUT_ROOT = {
    "external": Path("results/rebuttal/intensity"),
    "rag":      Path("results/rebuttal/intensity_rag"),
    "history":  Path("results/rebuttal/intensity_history"),
}
DEFAULT_OUT = Path("results/rebuttal/intensity_pathway")

INTENSITY_ORDER = ("plausible_mild", "plausible", "plausible_strong")
INTENSITY_LABEL = {
    "plausible_mild": "Mild",
    "plausible": "Standard",
    "plausible_strong": "Strong",
}


def gather() -> list[dict]:
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for suite in SUITES:
        root = INPUT_ROOT[suite]
        if not root.exists():
            log.warning("Missing root for suite %s: %s", suite, root)
            continue
        for model_dir in sorted(root.iterdir()):
            if not model_dir.is_dir() or model_dir.name.startswith("_"):
                continue
            curve_path = model_dir / "intensity_curve.json"
            if not curve_path.exists():
                log.warning("Missing intensity_curve.json for %s/%s",
                            suite, model_dir.name)
                continue
            curve = json.loads(curve_path.read_text())
            rows.append({
                "suite": suite,
                "model": MODEL_SHORT.get(model_dir.name, model_dir.name),
                "model_slug": model_dir.name,
                "uai_mild":     curve.get("plausible_mild"),
                "uai_standard": curve.get("plausible"),
                "uai_strong":   curve.get("plausible_strong"),
                "n_mild":       curve.get("plausible_mild_n"),
                "n_standard":   curve.get("plausible_n"),
                "n_strong":     curve.get("plausible_strong_n"),
            })
    return rows


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Group by model -> suite -> {mild,standard,strong}
    by_model: dict[str, dict[str, dict]] = {}
    for r in rows:
        by_model.setdefault(r["model"], {})[r["suite"]] = r

    lines = [
        r"% Auto-generated by anchorbench.analysis.intensity_pathway",
        r"% Cross-pathway intensity: matched mild/standard/strong "
        r"credibility on External, RAG, History.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrr rrr rrr}",
        r"\toprule",
        r"\multirow{2}{*}{Model} & \multicolumn{3}{c}{External} "
        r"& \multicolumn{3}{c}{RAG} & \multicolumn{3}{c}{History} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
        r" & Mild & Std & Strong & Mild & Std & Strong "
        r"& Mild & Std & Strong \\",
        r"\midrule",
    ]
    for model in sorted(by_model.keys()):
        cells = [model]
        for suite in SUITES:
            r = by_model[model].get(suite, {})
            cells.append(fmt_latex(r.get("uai_mild")))
            cells.append(fmt_latex(r.get("uai_standard")))
            cells.append(fmt_latex(r.get("uai_strong")))
        lines.append("  " + " & ".join(cells) + r" \\")

    # Mean row per suite
    def _mean_by_suite(intensity_key: str) -> dict[str, float | None]:
        out: dict[str, float | None] = {}
        for suite in SUITES:
            vs = [
                by_model[m].get(suite, {}).get(intensity_key)
                for m in by_model
            ]
            vs = [v for v in vs if v is not None]
            out[suite] = (sum(vs) / len(vs)) if vs else None
        return out

    mm = _mean_by_suite("uai_mild")
    ms = _mean_by_suite("uai_standard")
    mg = _mean_by_suite("uai_strong")
    lines.append(r"\midrule")
    mean_cells = ["Mean"]
    for suite in SUITES:
        mean_cells.append(f"\\textbf{{{fmt_latex(mm[suite])}}}")
        mean_cells.append(f"\\textbf{{{fmt_latex(ms[suite])}}}")
        mean_cells.append(f"\\textbf{{{fmt_latex(mg[suite])}}}")
    lines.append("  " + " & ".join(mean_cells) + r" \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (r"\caption{Cross-pathway plausibility-intensity dose-response."
         r" The same mild/standard/strong source-credibility manipulation is"
         r" applied across three pathways. Positive Strong\,$>$\,Mild gaps"
         r" indicate models weight source credibility; near-flat curves at"
         r" high UAI indicate numeric anchoring dominates regardless of"
         r" source. UAI values are mean across the panel; details in"
         r" supplementary CSV.}"),
        r"\label{tab:intensity_pathway}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")


def write_figure(rows: list[dict], path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        log.warning("matplotlib unavailable; skipping figure")
        return
    by_suite: dict[str, list[dict]] = {s: [] for s in SUITES}
    for r in rows:
        by_suite.setdefault(r["suite"], []).append(r)

    fig, axes = plt.subplots(1, 3, figsize=(11.5, 3.2), sharey=True)
    x = list(range(3))
    xlabels = [INTENSITY_LABEL[k] for k in INTENSITY_ORDER]
    for ax, suite in zip(axes, SUITES):
        for r in sorted(by_suite[suite], key=lambda r: r["model"]):
            y = [r.get("uai_mild"), r.get("uai_standard"), r.get("uai_strong")]
            if all(v is None for v in y):
                continue
            ax.plot(x, y, marker="o", linewidth=1.3, markersize=4,
                    label=r["model"])
        ax.axhline(1 / 6, color="grey", linestyle=":", linewidth=0.8)
        ax.axhline(0, color="black", linewidth=0.5)
        ax.set_xticks(x)
        ax.set_xticklabels(xlabels)
        ax.set_title(SUITE_LABEL[suite])
        ax.grid(True, axis="y", linewidth=0.3, alpha=0.5)
    axes[0].set_ylabel("UAI (mean across items)")
    axes[1].set_xlabel("Source credibility")
    axes[-1].legend(loc="upper left", fontsize=7, frameon=False)
    fig.tight_layout()
    fig.savefig(path)
    fig.savefig(path.with_suffix(".pdf"))
    import matplotlib.pyplot as plt2
    plt2.close(fig)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    by_suite: dict[str, list[dict]] = {s: [] for s in SUITES}
    for r in rows:
        by_suite.setdefault(r["suite"], []).append(r)

    lines = [
        "# Cross-pathway plausibility-intensity\n\n",
        "Matched source-credibility intensity across pathways, on the "
        "same graded-relevance axis.\n\n",
        "Same 3-point source-credibility scale (mild / standard / strong) "
        "applied to three pathways:\n\n",
        "- External: preamble injected before the question.\n",
        "- RAG: preamble forms the body of the anchored retrieved doc.\n",
        "- History: preamble injected at Stage 2 alongside the complete "
        "evidence (compounds with the model-generated self-anchor).\n\n",
        "## Per-pathway dose-response (mean UAI)\n\n",
        "| Pathway | Mild | Standard | Strong | Δ(strong-mild) |\n",
        "|---|---:|---:|---:|---:|\n",
    ]
    for suite in SUITES:
        bs = by_suite.get(suite, [])
        if not bs:
            continue

        def _mean(key: str, bs=bs) -> float | None:
            vs = [r[key] for r in bs
                  if r.get(key) is not None and isinstance(r[key], (int, float))]
            return (sum(vs) / len(vs)) if vs else None

        mm, ms, mg = _mean("uai_mild"), _mean("uai_standard"), _mean("uai_strong")
        delta = (mg - mm) if (mg is not None and mm is not None) else None
        lines.append(
            f"| {SUITE_LABEL[suite]} | {fmt_latex(mm)} | {fmt_latex(ms)} | "
            f"{fmt_latex(mg)} | {fmt_latex(delta)} |\n"
        )
    lines.append("\n## Interpretation\n\n")
    lines.append(
        "A monotone Mild < Standard < Strong curve indicates the model "
        "weights source credibility (consistent with rational Bayesian "
        "updating). A flat-but-high curve indicates classical "
        "number-anchoring (the numeric value drives the shift "
        "independent of source). Cross-pathway: if the *shape* of the "
        "intensity curve is preserved across pathways, the underlying "
        "credibility-sensitivity mechanism is pathway-invariant.\n"
    )
    path.write_text("".join(lines))


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="Cross-pathway intensity analysis")
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather()
    log.info("Gathered %d (suite,model) rows", len(rows))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "intensity_pathway.csv")
    write_json(rows, args.out_dir / "intensity_pathway.json")
    write_latex(rows, args.out_dir / "intensity_pathway_table.tex")
    write_figure(rows, args.out_dir / "intensity_pathway.png")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
