"""Plausibility-intensity analysis.

Reads ``results/rebuttal/intensity/<model_slug>/intensity_curve.json`` for
every model and produces:
  - intensity.csv / intensity.json
  - intensity_table.tex
  - intensity.pdf / intensity.png (3-point dose-response curve)
  - interpretation.md
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from anchorbench.analysis._io import fmt, write_csv, write_json

log = logging.getLogger(__name__)

DEFAULT_IN = Path("results/rebuttal/intensity")
DEFAULT_OUT = Path("results/rebuttal/intensity")

INTENSITY_ORDER = ("plausible_mild", "plausible", "plausible_strong")
INTENSITY_LABELS = {
    "plausible_mild": "Mild",
    "plausible": "Standard",
    "plausible_strong": "Strong",
}


def gather(in_dir: Path) -> list[dict]:
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for model_dir in sorted(in_dir.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        slug = model_dir.name
        curve_path = model_dir / "intensity_curve.json"
        if not curve_path.exists():
            log.warning("Missing intensity_curve.json for %s", slug)
            continue
        curve = json.loads(curve_path.read_text())
        row = {
            "model": MODEL_SHORT.get(slug, slug),
            "model_slug": slug,
            "uai_mild": curve.get("plausible_mild"),
            "uai_standard": curve.get("plausible"),
            "uai_strong": curve.get("plausible_strong"),
            "n_mild": curve.get("plausible_mild_n"),
            "n_standard": curve.get("plausible_n"),
            "n_strong": curve.get("plausible_strong_n"),
        }
        rows.append(row)
    return rows


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by anchorbench.analysis.intensity",
        r"% Plausible-anchor intensity dose-response.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{6pt}",
        r"\begin{tabular}{l rrr r}",
        r"\toprule",
        r"Model & UAI$_{\mathrm{mild}}$ & UAI$_{\mathrm{standard}}$ "
        r"& UAI$_{\mathrm{strong}}$ & $\Delta$ (strong - mild) \\",
        r"\midrule",
    ]
    rows_sorted = sorted(rows, key=lambda r: r["model"])
    for r in rows_sorted:
        delta = (
            r["uai_strong"] - r["uai_mild"]
            if r.get("uai_strong") is not None and r.get("uai_mild") is not None
            else None
        )
        lines.append(
            f"{r['model']} & {fmt(r['uai_mild'], 3, signed=True)} & "
            f"{fmt(r['uai_standard'], 3, signed=True)} & {fmt(r['uai_strong'], 3, signed=True)} & "
            f"{fmt(delta, 3, signed=True)} \\\\"
        )
    # Mean row
    def _mean(key: str) -> float | None:
        vs = [r[key] for r in rows
              if r.get(key) is not None and isinstance(r[key], (int, float))]
        return sum(vs) / len(vs) if vs else None
    mm, ms, msg = _mean("uai_mild"), _mean("uai_standard"), _mean("uai_strong")
    md = (msg - mm) if (msg is not None and mm is not None) else None
    lines.append(r"\midrule")
    lines.append(
        f"Mean & \\textbf{{{fmt(mm, 3, signed=True)}}} & \\textbf{{{fmt(ms, 3, signed=True)}}} & "
        f"\\textbf{{{fmt(msg, 3, signed=True)}}} & \\textbf{{{fmt(md, 3, signed=True)}}} \\\\"
    )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (
            r"\caption{Plausibility-intensity dose-response on External."
            r" Mild = single, hedged, unverified source"
            r" (`a back-of-envelope guess by a non-expert');"
            r" Standard = the published plausible condition"
            r" (`a preliminary analysis estimated');"
            r" Strong = multiple convergent peer-reviewed sources"
            r" (`three independent peer-reviewed studies have converged on')."
            r" A positive $\Delta$ (strong $>$ mild) is consistent with"
            r" rational weighting of source credibility; near-zero $\Delta$"
            r" with high absolute UAI indicates the anchor's numeric value"
            r" drives behavior independent of source.}"
        ),
        r"\label{tab:intensity}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote %s", path)


def write_figure(rows: list[dict], path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        log.warning("matplotlib unavailable; skipping figure %s", path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(5.0, 3.0))
    x = list(range(len(INTENSITY_ORDER)))
    labels = [INTENSITY_LABELS[k] for k in INTENSITY_ORDER]
    for r in sorted(rows, key=lambda r: r["model"]):
        y = [r.get(f"uai_{INTENSITY_LABELS[k].lower()}") for k in INTENSITY_ORDER]
        if all(v is None for v in y):
            continue
        ax.plot(x, y, marker="o", label=r["model"], linewidth=1.3, markersize=4)
    ax.axhline(1 / 6, color="grey", linestyle=":", linewidth=0.9,
               label="rational ceiling ($w{=}1$)")
    ax.axhline(0, color="black", linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_xlabel("Source credibility")
    ax.set_ylabel("UAI (mean)")
    ax.set_title("Plausible-anchor intensity dose-response (3 models, External)")
    ax.legend(loc="upper left", fontsize=8, frameon=False)
    ax.grid(True, axis="y", linewidth=0.3, alpha=0.5)
    fig.tight_layout()
    fig.savefig(path)
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)
    log.info("Wrote %s and PDF", path)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows_sorted = sorted(rows, key=lambda r: r["model"])

    def _mean(k: str) -> float | None:
        vs = [r[k] for r in rows if r.get(k) is not None
              and isinstance(r[k], (int, float))]
        return sum(vs) / len(vs) if vs else None

    mm, ms, msg = _mean("uai_mild"), _mean("uai_standard"), _mean("uai_strong")
    lines = [
        "# Plausibility-intensity probe\n\n",
        "Three-point dose-response with the SAME numeric anchor at three "
        "source-credibility levels:\n\n",
        "- **Mild**: \"A back-of-envelope guess by a non-expert ... not "
        "been validated\"\n",
        "- **Standard**: \"A preliminary analysis ... estimated\" "
        "(published plausible condition)\n",
        "- **Strong**: \"Three independent peer-reviewed studies have "
        "converged on ...\"\n\n",
        "## Headline numbers (mean across panel)\n\n",
        f"- mean UAI_mild = {fmt(mm, 3, signed=True)}\n",
        f"- mean UAI_standard = {fmt(ms, 3, signed=True)}\n",
        f"- mean UAI_strong = {fmt(msg, 3, signed=True)}\n",
    ]
    if all(v is not None for v in (mm, ms, msg)):
        lines.append(
            f"- mean \u0394(strong - mild) = {fmt(msg - mm, 3, signed=True)}\n"
        )
        monotone = mm <= ms <= msg
        lines.append(
            f"- Monotone mild $\\le$ standard $\\le$ strong? "
            f"**{'YES' if monotone else 'NO'}**.\n"
        )
    lines.append("\n## Per-model intensity curve\n\n")
    lines.append("| Model | Mild | Standard | Strong | \u0394 (strong-mild) |\n")
    lines.append("|---|---:|---:|---:|---:|\n")
    for r in rows_sorted:
        d = (r["uai_strong"] - r["uai_mild"]
             if r.get("uai_strong") is not None
             and r.get("uai_mild") is not None else None)
        lines.append(
            f"| {r['model']} | {fmt(r['uai_mild'], 3, signed=True)} | "
            f"{fmt(r['uai_standard'], 3, signed=True)} | {fmt(r['uai_strong'], 3, signed=True)} | "
            f"{fmt(d, 3, signed=True)} |\n"
        )
    lines.append(
        "\n## Interpretation\n\n"
        "A monotone increase mild < standard < strong with positive "
        "$\\Delta$(strong $-$ mild) indicates the model is at least "
        "partially weighting source credibility, consistent with "
        "rational Bayesian updating. A flat curve (mild $\\approx$ "
        "standard $\\approx$ strong) at high absolute UAI indicates "
        "the anchor's numeric value drives behavior independent of "
        "source credibility, i.e. classical anchoring bias.\n"
    )
    path.write_text("".join(lines))
    log.info("Wrote %s", path)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="D1 plausibility-intensity analysis")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather(args.in_dir)
    log.info("Gathered %d model rows from %s", len(rows), args.in_dir)
    if not rows:
        log.error("No rows; aborting")
        raise SystemExit(1)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "intensity.csv")
    write_json(rows, args.out_dir / "intensity.json")
    write_latex(rows, args.out_dir / "intensity_table.tex")
    write_figure(rows, args.out_dir / "intensity.png")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
