"""P2 RAG realism analysis.

Reads ``results/rebuttal/rag_realism/<slug>/realism_curve.json`` for every
model and emits:
  rag_realism.csv / .json
  rag_realism_table.tex
  rag_realism.pdf / .png  (rank-degradation bar chart)
  interpretation.md
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_IN = Path("results/rebuttal/rag_realism")
DEFAULT_OUT = Path("results/rebuttal/rag_realism")

TAGS = ("baseline", "rank1", "rank5", "rank5_distract")
TAG_LABEL = {
    "baseline":         "Baseline (rank 2)",
    "rank1":            "Rank 1",
    "rank5":            "Rank 5 + 2 distract.",
    "rank5_distract":   "Rank 5 + 2 distract. + rel scores",
}


def gather(in_dir: Path) -> list[dict]:
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for model_dir in sorted(in_dir.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        curve_path = model_dir / "realism_curve.json"
        if not curve_path.exists():
            continue
        curve = json.loads(curve_path.read_text())
        row = {
            "model": MODEL_SHORT.get(model_dir.name, model_dir.name),
            "model_slug": model_dir.name,
        }
        for rel in ("plausible", "irrelevant"):
            for tag in TAGS:
                row[f"{rel}_{tag}"] = curve.get(f"{rel}__{tag}")
        rows.append(row)
    return rows


def _fmt(v: float | None) -> str:
    if v is None:
        return "---"
    s = f"{v:+.2f}"
    if s.startswith("-"):
        return f"$-${s[1:]}"
    if s.startswith("+"):
        return s[1:]
    return s


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by anchorbench.analysis.rag_realism",
        r"% P2 RAG realism ablation: anchor-document rank x distractors.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrrr rrrr}",
        r"\toprule",
        r"\multirow{2}{*}{Model} & \multicolumn{4}{c}{Plausible (UAI)} "
        r"& \multicolumn{4}{c}{Irrelevant (UAI)} \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}",
        r" & Base & R1 & R5+D & R5+D+Sc & Base & R1 & R5+D & R5+D+Sc \\",
        r"\midrule",
    ]
    for r in sorted(rows, key=lambda r: r["model"]):
        cells = [r["model"]]
        for rel in ("plausible", "irrelevant"):
            for tag in TAGS:
                cells.append(_fmt(r.get(f"{rel}_{tag}")))
        lines.append("  " + " & ".join(cells) + r" \\")

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    mean_cells = ["Mean"]
    for rel in ("plausible", "irrelevant"):
        for tag in TAGS:
            mean_cells.append(f"\\textbf{{{_fmt(_col_mean(f'{rel}_{tag}'))}}}")
    lines.append(r"\midrule")
    lines.append("  " + " & ".join(mean_cells) + r" \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (r"\caption{P2 RAG realism ablation. Base = anchored doc at position 2"
         r" (published RAG layout); R1 = anchor at top of retrieval (rank 1);"
         r" R5+D = anchor at bottom of a 5-doc list with 2 plausible"
         r" distractor documents adjacent to the anchor; R5+D+Sc adds"
         r" synthetic per-doc relevance scores. A drop from R1 to R5+D"
         r" indicates models down-weight low-ranked retrieved anchors,"
         r" addressing reviewer REVIEWER-2 (RAG simplification).}"),
        r"\label{tab:rebuttal_rag_realism}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")


def write_figure(rows: list[dict], path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception:
        log.warning("matplotlib unavailable; skipping figure")
        return
    fig, ax = plt.subplots(figsize=(7.5, 3.2))
    x = np.arange(len(TAGS))
    width = 0.7 / max(1, len(rows))
    for i, r in enumerate(sorted(rows, key=lambda r: r["model"])):
        y = [r.get(f"plausible_{t}") for t in TAGS]
        y = [v if v is not None else 0.0 for v in y]
        ax.bar(x + (i - len(rows) / 2 + 0.5) * width, y, width,
               label=r["model"])
    ax.axhline(0, color="black", linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels([TAG_LABEL[t] for t in TAGS], rotation=15,
                       ha="right", fontsize=8)
    ax.set_ylabel("Plausible-anchor UAI (mean)")
    ax.set_title("RAG realism: anchor rank + distractors (P2)")
    ax.legend(fontsize=7, frameon=False, loc="upper right")
    fig.tight_layout()
    fig.savefig(path)
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    lines = [
        "# P2 — RAG realism ablation\n\n",
        "Addresses reviewer **REVIEWER-2**: the RAG suite varies document "
        "rank (1 vs 5), adds plausible distractors, and optionally "
        "exposes synthetic relevance scores.\n\n",
        "## Mean UAI across the panel\n\n",
        "| Relevance | Base (rank 2) | Rank 1 | Rank 5 + 2 distract. "
        "| Rank 5 + distract. + scores |\n",
        "|---|---:|---:|---:|---:|\n",
    ]
    for rel in ("plausible", "irrelevant"):
        lines.append(
            f"| {rel.capitalize()} | "
            f"{_fmt(_col_mean(f'{rel}_baseline'))} | "
            f"{_fmt(_col_mean(f'{rel}_rank1'))} | "
            f"{_fmt(_col_mean(f'{rel}_rank5'))} | "
            f"{_fmt(_col_mean(f'{rel}_rank5_distract'))} |\n"
        )
    lines.append(
        "\n## Interpretation\n\n"
        "If UAI is higher at Rank 1 than Rank 5, models privilege "
        "top-ranked retrieved documents (a property of realistic "
        "RAG systems) and the published RAG number is an "
        "intermediate estimate. If UAI drops when distractors are "
        "added, the anchored document's salience is reduced by "
        "surrounding context — meaning real-world RAG pipelines with "
        "diverse retrieval would observe weaker anchoring than the "
        "controlled benchmark. The R5+D+Sc column tests whether "
        "explicit relevance scores let models down-weight the "
        "anchor when its retrieval score is mid-pack.\n"
    )
    path.write_text("".join(lines))


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="P2 RAG realism analysis")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather(args.in_dir)
    log.info("Gathered %d rows", len(rows))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "rag_realism.csv")
    write_json(rows, args.out_dir / "rag_realism.json")
    write_latex(rows, args.out_dir / "rag_realism_table.tex")
    write_figure(rows, args.out_dir / "rag_realism.png")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
