"""Plausibility-spectrum analysis.

Reads ``results/rebuttal/spectrum/<model_slug>/results_extended.jsonl`` for
every model, computes extended metrics (control, irrelevant, plausible,
placebo, authority), and emits:

* ``spectrum.csv`` — long-format table with one row per (model, condition)
* ``spectrum.json`` — same data in JSON
* ``spectrum_table.tex`` — wide LaTeX table for the appendix
* ``spectrum.pdf`` / ``spectrum.png`` — 4-point plausibility curve figure
* ``interpretation.md`` — human-readable narrative

Run after ``anchorbench.runners.rebuttal_spectrum`` has produced extended
results for each model.
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_IN = Path("results/rebuttal/spectrum")
DEFAULT_OUT = Path("results/rebuttal/spectrum")

# Plausibility ordering used for x-axis of the curve figure.
# Placebo and irrelevant are both "the anchor carries no relevant information"
# (placebo = page count / days, irrelevant = case #); we order placebo first
# because it is slightly closer to a real signal (numerical and noun-paired).
SPECTRUM_ORDER = ("placebo", "irr", "plaus", "authority")

# Display labels (used for figure x-axis and markdown headings)
SPECTRUM_LABELS = {
    "placebo": "Placebo",
    "irr": "Irrelevant",
    "plaus": "Plausible",
    "authority": "Authority",
}


def _load_summary(p: Path) -> dict | None:
    if not p.exists():
        return None
    return json.loads(p.read_text())


def _format_ci(c: dict | None) -> str:
    if not c or c.get("mean") is None:
        return "---"
    m = c["mean"]
    lo = c.get("lo")
    hi = c.get("hi")
    if lo is None or hi is None:
        return f"{m:+.2f}"
    return f"{m:+.2f} [{lo:+.2f}, {hi:+.2f}]"


def gather_rows(in_dir: Path) -> list[dict]:
    """Walk in_dir and return one row per (model, condition_group)."""
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for model_dir in sorted(in_dir.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        slug = model_dir.name
        short = MODEL_SHORT.get(slug, slug)
        summary = _load_summary(model_dir / "summary_extended.json")
        if summary is None:
            log.warning("Missing summary_extended.json for %s", slug)
            continue
        row = {
            "model": short,
            "model_slug": slug,
            "n_items": summary.get("n_items"),
            "mae_control": summary.get("mae_control"),
            "acc10_control": summary.get("acc10_control"),
        }
        for k in SPECTRUM_ORDER:
            ci = summary.get(f"uai_{k}_ci")
            if ci:
                row[f"uai_{k}"] = ci.get("mean")
                row[f"uai_{k}_lo"] = ci.get("lo")
                row[f"uai_{k}_hi"] = ci.get("hi")
            else:
                row[f"uai_{k}"] = summary.get(f"uai_{k}")
        rows.append(row)
    return rows


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        return
    keys = sorted({k for r in rows for k in r.keys()})
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    log.info("Wrote %s (%d rows)", path, len(rows))


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))
    log.info("Wrote %s", path)


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by anchorbench.analysis.spectrum",
        r"% 4-point plausibility spectrum on External.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrrr}",
        r"\toprule",
        r"Model & UAI$_{\mathrm{placebo}}$ & UAI$_{\mathrm{irr}}$ "
        r"& UAI$_{\mathrm{pls}}$ & UAI$_{\mathrm{auth}}$ \\",
        r"\midrule",
    ]
    rows_sorted = sorted(rows, key=lambda r: r["model"])
    for r in rows_sorted:
        cells = [r["model"]]
        for k in SPECTRUM_ORDER:
            v = r.get(f"uai_{k}")
            cells.append("---" if v is None else f"{v:+.2f}")
        lines.append(" & ".join(cells) + r" \\")
    # mean row
    means = {}
    for k in SPECTRUM_ORDER:
        vals = [r[f"uai_{k}"] for r in rows
                if r.get(f"uai_{k}") is not None
                and isinstance(r[f"uai_{k}"], (int, float))]
        means[k] = sum(vals) / len(vals) if vals else None
    lines.append(r"\midrule")
    lines.append(
        "Mean & "
        + " & ".join(
            "---" if means[k] is None else f"\\textbf{{{means[k]:+.2f}}}"
            for k in SPECTRUM_ORDER
        )
        + r" \\"
    )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (
            r"\caption{Plausibility spectrum on External: mean UAI for each"
            r" of four anchor types --- placebo (anchor refers to an"
            r" extraneous numeric property such as document length),"
            r" irrelevant (case-number anchor),"
            r" plausible (``a recent report suggested $\sim$23''), and"
            r" authority (``a panel of senior analysts estimated $\sim$23'')."
            r" A monotone increase along the plausibility axis would be"
            r" consistent with rational use of source credibility;"
            r" any positive UAI on the placebo column is unambiguously"
            r" anchoring bias.}"
        ),
        r"\label{tab:plausibility_spectrum}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote %s", path)


def write_figure(rows: list[dict], path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        log.warning("matplotlib unavailable; skipping figure %s", path)
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(5.5, 3.2))
    x = list(range(len(SPECTRUM_ORDER)))
    labels = [SPECTRUM_LABELS[k] for k in SPECTRUM_ORDER]
    rows_sorted = sorted(rows, key=lambda r: r["model"])

    for r in rows_sorted:
        y = [r.get(f"uai_{k}") for k in SPECTRUM_ORDER]
        if all(v is None for v in y):
            continue
        ax.plot(x, y, marker="o", label=r["model"], linewidth=1.3, markersize=4)

    # Reference line at the w=1 rational ceiling (1/6)
    ax.axhline(1 / 6, color="grey", linestyle=":",
               linewidth=0.9, label="rational ceiling ($w{=}1$)")
    ax.axhline(0, color="black", linewidth=0.5)

    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_xlabel("Anchor type (low \u2192 high plausibility)")
    ax.set_ylabel("UAI (mean)")
    ax.set_title("Plausibility spectrum on External (5-model panel)")
    ax.legend(loc="upper left", fontsize=7, frameon=False, ncol=2)
    ax.grid(True, axis="y", linewidth=0.3, alpha=0.5)
    fig.tight_layout()
    fig.savefig(path)
    pdf_path = path.with_suffix(".pdf")
    fig.savefig(pdf_path)
    plt.close(fig)
    log.info("Wrote %s and %s", path, pdf_path)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows_sorted = sorted(rows, key=lambda r: r["model"])

    def _mean(key: str) -> float | None:
        vals = [r[key] for r in rows
                if r.get(key) is not None and isinstance(r[key], (int, float))]
        return sum(vals) / len(vals) if vals else None

    lines = [
        "# Plausibility spectrum\n\n",
        "Four-point spectrum on External: placebo / irrelevant / "
        "plausible / authority.\n\n",
        "## Headline numbers (mean across panel)\n\n",
    ]
    for k in SPECTRUM_ORDER:
        v = _mean(f"uai_{k}")
        if v is not None:
            lines.append(f"- mean UAI_{SPECTRUM_LABELS[k].lower()} = {v:+.3f}\n")

    # Monotone increase check
    means = [_mean(f"uai_{k}") for k in SPECTRUM_ORDER]
    if all(v is not None for v in means):
        monotone = all(means[i + 1] >= means[i] for i in range(len(means) - 1))
        lines.append(
            f"\nMonotone increase placebo < irrelevant < plausible < authority? "
            f"**{'YES' if monotone else 'NO'}**.\n"
        )
        lines.append(
            "A monotone increase would be consistent with the model "
            "rationally weighting source credibility; non-monotonicity "
            "(especially placebo close to irrelevant) is strong evidence of "
            "anchoring on the numeric value itself rather than its source.\n"
        )
    lines.append("\n## Per-model spectrum\n\n")
    lines.append(
        "| Model | " + " | ".join(SPECTRUM_LABELS[k] for k in SPECTRUM_ORDER) + " |\n"
    )
    lines.append("|---|---:|---:|---:|---:|\n")
    for r in rows_sorted:
        cells = ["---" if r.get(f"uai_{k}") is None
                 else f"{r[f'uai_{k}']:+.2f}"
                 for k in SPECTRUM_ORDER]
        lines.append(f"| {r['model']} | " + " | ".join(cells) + " |\n")

    # How often does placebo > 0 (bias above pure-noise)?
    placebo_pos = sum(
        1 for r in rows if (r.get("uai_placebo") or 0) > 0.05
    )
    lines.append(
        f"\n## Bias-above-noise check\n\n"
        f"- {placebo_pos}/{len(rows)} models have UAI_placebo > 0.05, "
        f"i.e., shift toward a numeric value that is *literally just the "
        f"document age in days*.\n"
    )
    path.write_text("".join(lines))
    log.info("Wrote %s", path)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="Plausibility-spectrum analysis (B2)")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather_rows(args.in_dir)
    log.info("Gathered %d model rows from %s", len(rows), args.in_dir)
    if not rows:
        log.error("No rows; aborting")
        raise SystemExit(1)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "spectrum.csv")
    write_json(rows, args.out_dir / "spectrum.json")
    write_latex(rows, args.out_dir / "spectrum_table.tex")
    write_figure(rows, args.out_dir / "spectrum.png")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
