"""P4 task-specification analysis.

Reads ``results/rebuttal/task_spec/external/<slug>/<strategy>/summary.json``
where strategy in {baseline, rule, judgment} and emits:
  task_spec.csv / .json
  task_spec_table.tex
  task_spec.pdf / .png (paired bars per model)
  interpretation.md
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_IN = Path("results/rebuttal/task_spec/external")
DEFAULT_OUT = Path("results/rebuttal/task_spec")
STRATEGIES = ("baseline", "rule", "judgment")
STRAT_LABEL = {
    "baseline": "Baseline",
    "rule":     "+Rule (arithmetic mean)",
    "judgment": "+Judgment (weighted avg)",
}


def gather(in_dir: Path) -> list[dict]:
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    if not in_dir.exists():
        log.warning("Missing %s", in_dir)
        return rows
    for model_dir in sorted(in_dir.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        row = {
            "model": MODEL_SHORT.get(model_dir.name, model_dir.name),
            "model_slug": model_dir.name,
        }
        for strat in STRATEGIES:
            s_path = model_dir / strat / "summary.json"
            if not s_path.exists():
                continue
            s = json.loads(s_path.read_text())
            row[f"uai_pls_{strat}"] = s.get("uai_plaus")
            row[f"uai_irr_{strat}"] = s.get("uai_irr")
            row[f"acc10_{strat}"]   = s.get("acc10_control")
        rows.append(row)
    return rows


def _fmt(v: float | None) -> str:
    if v is None:
        return "---"
    s = f"{v:+.2f}"
    if s.startswith("-"):
        return f"$-${s[1:]}"
    if s.startswith("+"):
        return s[1:]
    return s


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = list(rows[0].keys())
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by anchorbench.analysis.task_spec",
        r"% P4 task-specification ablation. Closes REVIEWER-2.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrr rrr}",
        r"\toprule",
        r"\multirow{2}{*}{Model} & \multicolumn{3}{c}{UAI$_{\mathrm{pls}}$} "
        r"& \multicolumn{3}{c}{UAI$_{\mathrm{irr}}$} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r" & Baseline & +Rule & +Judgment "
        r"& Baseline & +Rule & +Judgment \\",
        r"\midrule",
    ]
    for r in sorted(rows, key=lambda r: r["model"]):
        cells = [r["model"]]
        for metric in ("uai_pls", "uai_irr"):
            for strat in STRATEGIES:
                cells.append(_fmt(r.get(f"{metric}_{strat}")))
        lines.append("  " + " & ".join(cells) + r" \\")

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    mean_cells = ["Mean"]
    for metric in ("uai_pls", "uai_irr"):
        for strat in STRATEGIES:
            mean_cells.append(f"\\textbf{{{_fmt(_col_mean(f'{metric}_{strat}'))}}}")
    lines.append(r"\midrule")
    lines.append("  " + " & ".join(mean_cells) + r" \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (r"\caption{P4 task-specification ablation on External. Baseline ="
         r" published prompt (return integer only); +Rule appends"
         r" `Your estimate should be the unweighted arithmetic mean of the"
         r" visible ratings'; +Judgment appends `Your estimate should be a"
         r" weighted average ... weighting each piece according to which"
         r" sources you find more or less credible'. A drop from Baseline"
         r" to +Rule indicates the published anchoring effect is partly"
         r" driven by task underspecification (closes reviewer REVIEWER-2).}"),
        r"\label{tab:rebuttal_task_spec}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")


def write_figure(rows: list[dict], path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception:
        log.warning("matplotlib unavailable; skipping figure")
        return
    fig, ax = plt.subplots(figsize=(7.0, 3.0))
    rows_sorted = sorted(rows, key=lambda r: r["model"])
    n = len(rows_sorted)
    x = np.arange(len(STRATEGIES))
    width = 0.8 / max(1, n)
    for i, r in enumerate(rows_sorted):
        y = [r.get(f"uai_pls_{s}", 0.0) or 0.0 for s in STRATEGIES]
        ax.bar(x + (i - n / 2 + 0.5) * width, y, width, label=r["model"])
    ax.axhline(1 / 6, color="grey", linestyle=":", linewidth=0.8,
               label="rational ceiling ($w{=}1$)")
    ax.axhline(0, color="black", linewidth=0.5)
    ax.set_xticks(x)
    ax.set_xticklabels([STRAT_LABEL[s] for s in STRATEGIES], fontsize=8)
    ax.set_ylabel("UAI$_{plausible}$ (External)")
    ax.set_title("P4 — task-specification ablation")
    ax.legend(fontsize=7, frameon=False, loc="upper right")
    fig.tight_layout()
    fig.savefig(path)
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    lines = [
        "# P4 — Task-specification ablation\n\n",
        "Addresses reviewer **REVIEWER-2** (weak-model low control accuracy may "
        "reflect task confusion rather than anchoring) and reinforces "
        "answers to **REVIEWER-1** (gold = arithmetic mean) and "
        "**REVIEWER-1** (task realism).\n\n",
        "Two new prompt suffixes on External, alongside the published "
        "baseline prompt:\n\n",
        "- `+rule`: \"Your estimate should be the unweighted arithmetic "
        "mean of the visible ratings, rounded to the nearest integer.\"\n",
        "- `+judgment`: \"Your estimate should be a weighted average of "
        "the available evidence, weighting each piece according to which "
        "sources you find more or less credible.\"\n\n",
        "## Mean across panel\n\n",
        "| Metric | Baseline | +Rule | +Judgment |\n",
        "|---|---:|---:|---:|\n",
    ]
    for metric, label in (("uai_pls", "UAI_plausible"), ("uai_irr", "UAI_irrelevant")):
        lines.append(
            f"| {label} | "
            f"{_fmt(_col_mean(f'{metric}_baseline'))} | "
            f"{_fmt(_col_mean(f'{metric}_rule'))} | "
            f"{_fmt(_col_mean(f'{metric}_judgment'))} |\n"
        )
    lines.append(
        "\n## Interpretation\n\n"
        "- **+Rule vs Baseline**: a meaningful drop in UAI_pls under "
        "the explicit-rule prompt indicates the published anchoring "
        "effect is partly attributable to task underspecification "
        "rather than to a deep numerical-anchoring tendency. "
        "Importantly, *some* residual UAI_pls under +Rule is the "
        "bias-attributable portion that cannot be explained by "
        "confusion alone.\n"
        "- **+Judgment vs Baseline**: this serves as an upper-bound "
        "check; the explicit invitation to weight sources should "
        "raise UAI_pls toward (but not above) the Bayesian rational "
        "ceiling computed in Table 4 (A1).\n"
        "- **UAI_irr** should be near-zero across all three "
        "conditions for capable models — irrelevant anchors should "
        "remain ignored regardless of task framing.\n"
    )
    path.write_text("".join(lines))


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="P4 task-spec analysis")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather(args.in_dir)
    log.info("Gathered %d rows", len(rows))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "task_spec.csv")
    write_json(rows, args.out_dir / "task_spec.json")
    write_latex(rows, args.out_dir / "task_spec_table.tex")
    write_figure(rows, args.out_dir / "task_spec.png")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
