"""Tool realism analysis.

Reads ``results/rebuttal/tool_realism/<slug>/realism_curve.json`` and emits:
  tool_realism.csv / .json
  tool_realism_table.tex
  interpretation.md
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_IN = Path("results/rebuttal/tool_realism")
DEFAULT_OUT = Path("results/rebuttal/tool_realism")

TAGS = ("baseline", "elicited", "noisy")
TAG_LABEL = {
    "baseline":  "Baseline (externally injected)",
    "elicited":  "Model-elicited call",
    "noisy":     "Noisy tool envelope",
}


def gather(in_dir: Path) -> list[dict]:
    from anchorbench.eval.constants import MODEL_SHORT
    rows: list[dict] = []
    for model_dir in sorted(in_dir.iterdir()):
        if not model_dir.is_dir() or model_dir.name.startswith("_"):
            continue
        curve_path = model_dir / "realism_curve.json"
        if not curve_path.exists():
            continue
        curve = json.loads(curve_path.read_text())
        row = {
            "model": MODEL_SHORT.get(model_dir.name, model_dir.name),
            "model_slug": model_dir.name,
        }
        for rel in ("plausible", "irrelevant"):
            for tag in TAGS:
                row[f"{rel}_{tag}"] = curve.get(f"{rel}__{tag}")
        rows.append(row)
    return rows


def _fmt(v: float | None) -> str:
    if v is None:
        return "---"
    s = f"{v:+.2f}"
    if s.startswith("-"):
        return f"$-${s[1:]}"
    if s.startswith("+"):
        return s[1:]
    return s


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        r"% Auto-generated by anchorbench.analysis.tool_realism",
        r"% Tool realism: model-elicited vs externally injected tool calls;"
        r" plus noisy tool envelope.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrr rrr}",
        r"\toprule",
        r"\multirow{2}{*}{Model} & \multicolumn{3}{c}{Plausible (UAI)} "
        r"& \multicolumn{3}{c}{Irrelevant (UAI)} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r" & Base & Elicited & Noisy & Base & Elicited & Noisy \\",
        r"\midrule",
    ]
    for r in sorted(rows, key=lambda r: r["model"]):
        cells = [r["model"]]
        for rel in ("plausible", "irrelevant"):
            for tag in TAGS:
                cells.append(_fmt(r.get(f"{rel}_{tag}")))
        lines.append("  " + " & ".join(cells) + r" \\")

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    mean_cells = ["Mean"]
    for rel in ("plausible", "irrelevant"):
        for tag in TAGS:
            mean_cells.append(f"\\textbf{{{_fmt(_col_mean(f'{rel}_{tag}'))}}}")
    lines.append(r"\midrule")
    lines.append("  " + " & ".join(mean_cells) + r" \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (r"\caption{Tool realism ablation. Base reproduces the published"
         r" Tool suite (externally injected tool output); Elicited prepends a"
         r" synthetic model-planned tool-call turn (provenance signal);"
         r" Noisy wraps the anchor value in a realistic JSON envelope"
         r" containing additional metadata fields. Closing the gap between"
         r" Base and Elicited indicates the anchor effect is not driven by"
         r" the externally-injected framing; reductions under Noisy"
         r" indicate the anchor's salience competes with surrounding"
         r" metadata.}"),
        r"\label{tab:tool_realism}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    def _col_mean(key: str) -> float | None:
        vs = [r.get(key) for r in rows]
        vs = [v for v in vs if v is not None and isinstance(v, (int, float))]
        return (sum(vs) / len(vs)) if vs else None

    lines = [
        "# Tool realism ablation\n\n",
        "Varies two tool-realism axes:\n\n",
        "- **Elicited**: a synthetic assistant turn announces the lookup "
        "before the tool call, framing the response as model-initiated.\n",
        "- **Noisy**: the tool response wraps the anchor value in a "
        "realistic envelope with extra metadata fields (`confidence`, "
        "`freshness_days`, `sample_size_n`, `request_timestamp_ms`, "
        "etc.) to test salience-of-number.\n\n",
        "## Mean UAI across the panel\n\n",
        "| Relevance | Baseline | Elicited | Noisy |\n",
        "|---|---:|---:|---:|\n",
    ]
    for rel in ("plausible", "irrelevant"):
        lines.append(
            f"| {rel.capitalize()} | "
            f"{_fmt(_col_mean(f'{rel}_baseline'))} | "
            f"{_fmt(_col_mean(f'{rel}_elicited'))} | "
            f"{_fmt(_col_mean(f'{rel}_noisy'))} |\n"
        )
    lines.append(
        "\n## Interpretation\n\n"
        "- If `Elicited` ≈ `Baseline`, the published Tool number is "
        "robust to the provenance signal (and the controlled "
        "externally-injected setup is a fair test).\n"
        "- If `Noisy` < `Baseline` plausibly, the published Tool "
        "number slightly overstates the in-practice anchoring effect "
        "because realistic tool responses dilute the anchor's "
        "salience.\n"
        "- If `Noisy` ≈ `Baseline`, anchoring is driven by the "
        "numeric value regardless of surrounding metadata — "
        "the bias is real even in production-style tool envelopes.\n"
    )
    path.write_text("".join(lines))


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="P3 Tool realism analysis")
    p.add_argument("--in_dir", type=Path, default=DEFAULT_IN)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather(args.in_dir)
    log.info("Gathered %d rows", len(rows))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "tool_realism.csv")
    write_json(rows, args.out_dir / "tool_realism.json")
    write_latex(rows, args.out_dir / "tool_realism_table.tex")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
