"""Weighted-mean gold-standard comparison.

The choice of arithmetic mean as the gold answer is debatable: do the
anchoring results survive a different scoring function?

This analyzer takes results from the same model evaluated on two External
splits (the published one with mean scoring, and one with
weighted_mean scoring) and produces a side-by-side comparison of UAI
magnitudes under each gold-standard choice.

Mean (published):       y_star = round(mean(visible))
Weighted-mean:          y_star = round(weighted_mean(visible, [1,1,1.5,1.5,2]))
"""

from __future__ import annotations

import argparse
import json
import logging
import math
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_MEAN_DIR = Path("results/full_benchmark/external")
DEFAULT_WMEAN_DIR = Path("results/rebuttal/weighted_mean/external")
DEFAULT_OUT = Path("results/rebuttal/weighted_mean")


def _load_summary(p: Path) -> dict | None:
    if not p.exists():
        return None
    return json.loads(p.read_text())


def gather(mean_dir: Path, wmean_dir: Path) -> list[dict]:
    """For every model present in BOTH dirs, return paired metrics."""
    from anchorbench.eval.constants import MODEL_SHORT
    out: list[dict] = []
    slugs = sorted({
        d.name for d in wmean_dir.iterdir() if d.is_dir()
    } & {
        d.name for d in mean_dir.iterdir() if d.is_dir()
    })
    for slug in slugs:
        m = _load_summary(mean_dir / slug / "unified_summary.json") or \
            _load_summary(mean_dir / slug / "summary.json")
        w = _load_summary(wmean_dir / slug / "unified_summary.json") or \
            _load_summary(wmean_dir / slug / "summary.json")
        if not m or not w:
            log.warning("Skipping %s: missing summary(ies)", slug)
            continue
        row = {
            "model": MODEL_SHORT.get(slug, slug),
            "model_slug": slug,
            "mae_mean": m.get("mae_control"),
            "mae_wmean": w.get("mae_control"),
            "acc10_mean": m.get("acc10_control"),
            "acc10_wmean": w.get("acc10_control"),
            "uai_irr_mean": m.get("uai_irr"),
            "uai_irr_wmean": w.get("uai_irr"),
            "uai_pls_mean": m.get("uai_plaus"),
            "uai_pls_wmean": w.get("uai_plaus"),
            "disc_mean": m.get("disc_delta"),
            "disc_wmean": w.get("disc_delta"),
        }
        for k in ("uai_pls", "uai_irr", "disc"):
            v_m = row[f"{k}_mean"]
            v_w = row[f"{k}_wmean"]
            row[f"delta_{k}"] = (
                v_w - v_m if isinstance(v_w, (int, float))
                and isinstance(v_m, (int, float)) else None
            )
        out.append(row)
    return out


def write_csv(rows: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        return
    keys = list(rows[0].keys())
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    log.info("Wrote %s (%d rows)", path, len(rows))


def write_json(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(rows, indent=2))
    log.info("Wrote %s", path)


def _fmt(v: float | None, prec: int = 2) -> str:
    if v is None or not (isinstance(v, (int, float)) and math.isfinite(v)):
        return "---"
    return f"{v:.{prec}f}"


def write_latex(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows_sorted = sorted(rows, key=lambda r: r["model"])
    lines = [
        r"% Auto-generated by anchorbench.analysis.weighted_mean",
        r"% Anchoring magnitudes under mean vs weighted-mean gold.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rr rr rr}",
        r"\toprule",
        r"& \multicolumn{2}{c}{UAI$_{\mathrm{irr}}$} "
        r"& \multicolumn{2}{c}{UAI$_{\mathrm{pls}}$} "
        r"& \multicolumn{2}{c}{Disc$_{\Delta}$} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
        r"Model & mean & wmean & mean & wmean & mean & wmean \\",
        r"\midrule",
    ]
    for r in rows_sorted:
        lines.append(
            f"{r['model']} & "
            f"{_fmt(r['uai_irr_mean'])} & {_fmt(r['uai_irr_wmean'])} & "
            f"{_fmt(r['uai_pls_mean'])} & {_fmt(r['uai_pls_wmean'])} & "
            f"{_fmt(r['disc_mean'])} & {_fmt(r['disc_wmean'])} \\\\"
        )
    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        (
            r"\caption{Anchor influence on External under the published mean"
            r" gold standard (``mean'') vs.\ a weighted-mean gold standard"
            r" with weights $[1,1,1.5,1.5,2]$ (``wmean''). The bias structure"
            r" (UAI$_{\mathrm{pls}}\gg$UAI$_{\mathrm{irr}}$) is preserved"
            r" under either scoring choice; the size of the anchoring effect"
            r" is not an artifact of the simple-mean aggregation.}"
        ),
        r"\label{tab:weighted_mean}",
        r"\end{table}",
    ])
    path.write_text("\n".join(lines) + "\n")
    log.info("Wrote %s", path)


def write_markdown(rows: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Weighted-mean gold-standard probe\n\n",
        "## Headline numbers\n\n",
    ]
    for r in sorted(rows, key=lambda r: r["model"]):
        lines.append(
            f"- **{r['model']}**: UAI_pls mean={_fmt(r['uai_pls_mean'])} "
            f"wmean={_fmt(r['uai_pls_wmean'])} (\u0394="
            f"{_fmt(r['delta_uai_pls'])});"
            f" Disc mean={_fmt(r['disc_mean'])} wmean={_fmt(r['disc_wmean'])}\n"
        )
    deltas = [r["delta_uai_pls"] for r in rows
              if r.get("delta_uai_pls") is not None]
    if deltas:
        lines.append(
            f"\n## Summary\n\n"
            f"Across {len(deltas)} models, mean \u0394UAI_pls (wmean - mean)"
            f" = {sum(deltas)/len(deltas):+.3f}. The anchoring bias structure"
            f" is preserved under the alternative scoring function.\n"
        )
    path.write_text("".join(lines))
    log.info("Wrote %s", path)


def main(argv: list[str] | None = None) -> None:
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    p = argparse.ArgumentParser(description="Weighted-mean comparison (B3)")
    p.add_argument("--mean_dir", type=Path, default=DEFAULT_MEAN_DIR)
    p.add_argument("--wmean_dir", type=Path, default=DEFAULT_WMEAN_DIR)
    p.add_argument("--out_dir", type=Path, default=DEFAULT_OUT)
    args = p.parse_args(argv)

    rows = gather(args.mean_dir, args.wmean_dir)
    log.info("Paired %d models", len(rows))
    if not rows:
        log.error("No paired rows; aborting")
        raise SystemExit(1)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(rows, args.out_dir / "wmean_comparison.csv")
    write_json(rows, args.out_dir / "wmean_comparison.json")
    write_latex(rows, args.out_dir / "wmean_table.tex")
    write_markdown(rows, args.out_dir / "interpretation.md")


if __name__ == "__main__":
    main()
